insert into universitate (nume_univ, oras) values ('Deakin University', 'Baykalovo');
insert into universitate (nume_univ, oras) values ('University of San Agustin', 'Liurenba');
insert into universitate (nume_univ, oras) values ('Universidad Autónoma de Fresnillo', 'Kobiernice');
insert into universitate (nume_univ, oras) values ('Sudan University for Science and Technology', 'Jauja');
insert into universitate (nume_univ, oras) values ('Gollis University', 'Weepanapi');
insert into universitate (nume_univ, oras) values ('Universidade de Santa Cruz do Sul', 'Antsirabe');
insert into universitate (nume_univ, oras) values ('Leading University', 'Jambean');
insert into universitate (nume_univ, oras) values ('Aichi Sangyo University', 'Negararatu');
insert into universitate (nume_univ, oras) values ('University of KwaZulu-Natal', 'Samaipata');
insert into universitate (nume_univ, oras) values ('Universidad de Playa Ancha de Ciencias de la Educacion', 'Pasirangin Tiga');
insert into universitate (nume_univ, oras) values ('Foreign Trade University', 'Lappajärvi');
insert into universitate (nume_univ, oras) values ('Universität Leipzig', 'Kobe');
insert into universitate (nume_univ, oras) values ('Universidade Regional do Noroeste do Estado do Rio Grande do Sul', 'Quatre Bornes');
insert into universitate (nume_univ, oras) values ('Fachhochschulstudiengänge Wels', 'Kruševac');
insert into universitate (nume_univ, oras) values ('Ecole Nationale Supérieure de Biologie Appliquée à la Nutrition et à l''Alementation', 'Valinhos');
insert into universitate (nume_univ, oras) values ('University of Toronto', 'Nizhnevartovsk');
insert into universitate (nume_univ, oras) values ('Dr. Bhim Rao Abdekar University', 'Singkup');
insert into universitate (nume_univ, oras) values ('Universidad la Concordia', 'Sanxi');
insert into universitate (nume_univ, oras) values ('Isik University', 'Matanog');
insert into universitate (nume_univ, oras) values ('Lebanon Valley College', 'Bačka Topola');
insert into universitate (nume_univ, oras) values ('Universidad Nacional Agraria La Selva', 'Tapacocha');
insert into universitate (nume_univ, oras) values ('University of the Visual & Performing Arts', 'Mucurapo');
insert into universitate (nume_univ, oras) values ('Anhui University of Finance and Economics', 'Megalochórion');
insert into universitate (nume_univ, oras) values ('Dokkyo University', 'Natal');
insert into universitate (nume_univ, oras) values ('Ching Kuo Institue of Management & Health', 'Yangzhou');
insert into universitate (nume_univ, oras) values ('University of Ancona', 'Houston');
insert into universitate (nume_univ, oras) values ('Manhattan School of Music', 'Castanheira');
insert into universitate (nume_univ, oras) values ('Ecole de l''Air', 'Cube');
insert into universitate (nume_univ, oras) values ('Kazak State University of Agriculture', 'Liuzikou');
insert into universitate (nume_univ, oras) values ('Barat College', 'Lengkongjaya');
insert into universitate (nume_univ, oras) values ('Ecole des Ingénieurs de la Ville de Paris', 'Anjia');
insert into universitate (nume_univ, oras) values ('Universidad Americana', 'Khōst');
insert into universitate (nume_univ, oras) values ('Shaheed Beheshti University', 'Xianglan');
insert into universitate (nume_univ, oras) values ('St.Cyril and Methodius University', 'Černošice');
insert into universitate (nume_univ, oras) values ('Samara State Aerospace University', 'Strömstad');
insert into universitate (nume_univ, oras) values ('Gotland University College', 'Zhoutian');
insert into universitate (nume_univ, oras) values ('National University of Computer & Emerging Sciences', 'Mâcon');
insert into universitate (nume_univ, oras) values ('Institute of Classical Studies, University of London', 'Taihe');
insert into universitate (nume_univ, oras) values ('University of Wah', 'Berģi');
insert into universitate (nume_univ, oras) values ('Universidad Nacional del Nordeste', 'Zongzhai');
insert into universitate (nume_univ, oras) values ('Universidad Técnica Estatal de Quevedo', 'Zambujeira');
insert into universitate (nume_univ, oras) values ('Al al-Bayt University', 'Garwolin');
insert into universitate (nume_univ, oras) values ('National Taiwan College of the Arts', 'Cabean');
insert into universitate (nume_univ, oras) values ('Libya Open University', 'San Agustín de Valle Fértil');
insert into universitate (nume_univ, oras) values ('Olive-Harvey College', 'Zebrzydowice');
insert into universitate (nume_univ, oras) values ('Lamar University - Port Arthur', 'Skien');
insert into universitate (nume_univ, oras) values ('Universidad Bernardo O''Higgins', 'Yafran');
insert into universitate (nume_univ, oras) values ('Adler School of Professional Psychology', 'Curahnongko');
insert into universitate (nume_univ, oras) values ('The Union Institute', 'Santa Iria de Azóia');
insert into universitate (nume_univ, oras) values ('South Carelian Polytechnic', 'Steinsel');
insert into universitate (nume_univ, oras) values ('Fudan University', 'Obukhiv');
insert into universitate (nume_univ, oras) values ('Medcenter One College of Nursing', 'Huazangsi');
insert into universitate (nume_univ, oras) values ('Gandhara Institute of Medical Sciences', 'Visby');
insert into universitate (nume_univ, oras) values ('Eastern Mediterranean University', 'Medicine Hat');
insert into universitate (nume_univ, oras) values ('Takestan Islamic Azad University', 'Bunawan');
insert into universitate (nume_univ, oras) values ('Ochanomizu Women''s University', 'Couva');
insert into universitate (nume_univ, oras) values ('Miyazaki Medical College', 'Banshu');
insert into universitate (nume_univ, oras) values ('University of Economics Varna', 'Itō');
insert into universitate (nume_univ, oras) values ('Nagoya University of Arts', 'Tampa');
insert into universitate (nume_univ, oras) values ('Fachhochschule Nordhessen', 'Sukorejo');
insert into universitate (nume_univ, oras) values ('College for Creative Studies', 'Bologna');
insert into universitate (nume_univ, oras) values ('International School of Management in Prešov', 'Köping');
insert into universitate (nume_univ, oras) values ('Champlain College', 'Made');
insert into universitate (nume_univ, oras) values ('Faculdade Jaguariúna', 'Cái Dầu');
insert into universitate (nume_univ, oras) values ('Kuban State University of Agriculture', 'Eusebio Ayala');
insert into universitate (nume_univ, oras) values ('Denison University', 'Pak Phli');
insert into universitate (nume_univ, oras) values ('Université de Kairouan', 'Pandakan');
insert into universitate (nume_univ, oras) values ('Bule Hora  University', 'Ögöömör');
insert into universitate (nume_univ, oras) values ('Sistema Universitario Ana G. Méndez', 'Rowokangkung');
insert into universitate (nume_univ, oras) values ('Nova Scotia College of Art and Design', 'Ani-e');
insert into universitate (nume_univ, oras) values ('MGH Institute of Health Professions', 'Nevers');
insert into universitate (nume_univ, oras) values ('Southern University - Baton Rouge', 'Megalochórion');
insert into universitate (nume_univ, oras) values ('Andon College - Stockton', 'Wilmington');
insert into universitate (nume_univ, oras) values ('University of North America', 'Linköping');
insert into universitate (nume_univ, oras) values ('Universitas 17 Agustus 1945 Cirebon', 'Rio do Sul');
insert into universitate (nume_univ, oras) values ('New Jersey City University', 'Temaiku Village');
insert into universitate (nume_univ, oras) values ('Millennia Atlantic University', 'Lianovérgi');
insert into universitate (nume_univ, oras) values ('Furman University', 'Wilkołaz');
insert into universitate (nume_univ, oras) values ('Wayamba University of Sri Lanka ', 'Blumbang');
insert into universitate (nume_univ, oras) values ('Northern Arizona University', 'Ogawa');
insert into universitate (nume_univ, oras) values ('American University in Cairo', 'Kallithéa');
insert into universitate (nume_univ, oras) values ('Al-Nasser University', 'Laborde');
insert into universitate (nume_univ, oras) values ('Meredith College', 'As Sūsah');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de San Martín', 'Marechal Cândido Rondon');
insert into universitate (nume_univ, oras) values ('Fukui University', 'Senhor do Bonfim');
insert into universitate (nume_univ, oras) values ('Universidad del Noreste', 'Zaraza');
insert into universitate (nume_univ, oras) values ('Hatyai University', 'La Foa');
insert into universitate (nume_univ, oras) values ('University of Maryland (System)', 'Louisville');
insert into universitate (nume_univ, oras) values ('University of Benin', 'Wangzuizi');
insert into universitate (nume_univ, oras) values ('Central State University', 'Khuan Don');
insert into universitate (nume_univ, oras) values ('University of Mostar', 'Nongba');
insert into universitate (nume_univ, oras) values ('Rivier College', 'Futian');
insert into universitate (nume_univ, oras) values ('University of South Bohemia', 'Daraitan');
insert into universitate (nume_univ, oras) values ('Sardarkrushinagar Dantiwada Agricultural University', 'Zhangdian');
insert into universitate (nume_univ, oras) values ('Unity College', 'Yongping');
insert into universitate (nume_univ, oras) values ('Universidade Católica de Santos', 'Xianghua');
insert into universitate (nume_univ, oras) values ('Huron University', 'Santa Cruz de Barahona');
insert into universitate (nume_univ, oras) values ('Universiti Tun Abdul Razak', 'Niquelândia');
insert into universitate (nume_univ, oras) values ('University of Verona', 'Uherce Mineralne');
insert into universitate (nume_univ, oras) values ('Tampere Polytechnic', 'Bordeaux');
insert into universitate (nume_univ, oras) values ('Schiller International University, Heidelberg', 'Prapen');
insert into universitate (nume_univ, oras) values ('Erasmus University Rotterdam', 'Kōnan');
insert into universitate (nume_univ, oras) values ('University of Witwatersrand', 'Stoczek Łukowski');
insert into universitate (nume_univ, oras) values ('Muadzam Shah Polytechnic', 'Cijoho');
insert into universitate (nume_univ, oras) values ('Technical University of Sofia', 'Hamburg');
insert into universitate (nume_univ, oras) values ('Universitas Sanata Dharma', 'Malakwal City');
insert into universitate (nume_univ, oras) values ('Tomsk State Pedagogical University', 'Puncakwangi');
insert into universitate (nume_univ, oras) values ('Ecole Supérieure de Commerce de Rouen', 'Tul’chyn');
insert into universitate (nume_univ, oras) values ('Universidad de Pamplona', 'Xam Nua');
insert into universitate (nume_univ, oras) values ('Ecole Nationale Supérieure de Biologie Appliquée à la Nutrition et à l''Alementation', 'Güines');
insert into universitate (nume_univ, oras) values ('Universidad Justo Sierra', 'Nikolayevsk');
insert into universitate (nume_univ, oras) values ('University of Latvia', 'Mangkon Daja');
insert into universitate (nume_univ, oras) values ('Escuela Superiore de Administración Pública', 'Pārūn');
insert into universitate (nume_univ, oras) values ('Fukui Prefectural University', 'Yên Lập');
insert into universitate (nume_univ, oras) values ('Inner Mongolia University', 'Kihurio');
insert into universitate (nume_univ, oras) values ('Marymount College New York', 'Jāsk');
insert into universitate (nume_univ, oras) values ('Taurida National V.I.Vernadsky University', 'San Ramon');
insert into universitate (nume_univ, oras) values ('Anhui Medical University', 'Houston');
insert into universitate (nume_univ, oras) values ('Nara Medical University', 'Petrokamenskoye');
insert into universitate (nume_univ, oras) values ('Universidad Técnica de Cotopaxi', 'Laç');
insert into universitate (nume_univ, oras) values ('Universidad de Los Andes', 'Pombal');
insert into universitate (nume_univ, oras) values ('Salisbury State University', 'Yeliguan');
insert into universitate (nume_univ, oras) values ('Takhatmal Shrivallabh Homoeopathic Medical College', 'Agía Triáda');
insert into universitate (nume_univ, oras) values ('The Government Sadiq College Women University Bahawalpur', 'Dongzaogang');
insert into universitate (nume_univ, oras) values ('Kazak National Technical University', 'Stockholm');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Tehran Medical', 'Mingyue');
insert into universitate (nume_univ, oras) values ('Universidad Don Vasco', 'Yangchengzhuang');
insert into universitate (nume_univ, oras) values ('Universitas Muhammadiyah Yogyakarta', 'Barreiras');
insert into universitate (nume_univ, oras) values ('İstanbul Şehir University', 'Catu');
insert into universitate (nume_univ, oras) values ('E.A.P. Europäische Wirtschaftshochschule Berlin', 'Skien');
insert into universitate (nume_univ, oras) values ('Institute of Teachers Education, Tawau', 'Revolucion');
insert into universitate (nume_univ, oras) values ('University of Central Punjab', 'Chiara');
insert into universitate (nume_univ, oras) values ('Texas A&M University - Corpus Christi', 'Capitán Sarmiento');
insert into universitate (nume_univ, oras) values ('University of Wisconsin - River Falls', 'Lycksele');
insert into universitate (nume_univ, oras) values ('Kazakh British Technical University', 'Sampir');
insert into universitate (nume_univ, oras) values ('University of Mindanao', 'Marinilla');
insert into universitate (nume_univ, oras) values ('Lagos State Polytechnic', 'Milín');
insert into universitate (nume_univ, oras) values ('Fountain University', 'Xiadong');
insert into universitate (nume_univ, oras) values ('Universidade da Madeira', 'Lurut');
insert into universitate (nume_univ, oras) values ('Mills Grae University', 'Sambongmulyo');
insert into universitate (nume_univ, oras) values ('Sunrise University Alwar', 'Jiahe');
insert into universitate (nume_univ, oras) values ('University of Lancaster', 'Liping');
insert into universitate (nume_univ, oras) values ('Great Lakes University of Kisumu', 'Baizhu');
insert into universitate (nume_univ, oras) values ('Tokyo University', 'Slovenska Bistrica');
insert into universitate (nume_univ, oras) values ('Point Loma Nazarene College', 'Banjar Laing');
insert into universitate (nume_univ, oras) values ('Otemon Gakuin University', 'Ushibuka');
insert into universitate (nume_univ, oras) values ('Hochschule Fulda', 'Sambogunung');
insert into universitate (nume_univ, oras) values ('Northern Sichuan Medical College', 'Kokkári');
insert into universitate (nume_univ, oras) values ('Rezekne Higher School', 'Yurino');
insert into universitate (nume_univ, oras) values ('Petro Mohyla Black Sea State University', 'Huangzhuang');
insert into universitate (nume_univ, oras) values ('University of Peshawar', 'Köping');
insert into universitate (nume_univ, oras) values ('Universidad Católica Tecnológica del Cibao', 'Alibago');
insert into universitate (nume_univ, oras) values ('Potti Sreeramulu Telugu University', 'Keleleng');
insert into universitate (nume_univ, oras) values ('Osaka Dental University', 'Chwałowice');
insert into universitate (nume_univ, oras) values ('Assumption University', 'Hutang');
insert into universitate (nume_univ, oras) values ('Konkuk University', 'Marialva');
insert into universitate (nume_univ, oras) values ('University of Economics Prague', 'Bulu');
insert into universitate (nume_univ, oras) values ('Eindhoven University of Technology', 'Kildare');
insert into universitate (nume_univ, oras) values ('University of Otago', 'Szczerców');
insert into universitate (nume_univ, oras) values ('University of Hormozgan', 'Bumpe');
insert into universitate (nume_univ, oras) values ('Helwan University', 'Chilecito');
insert into universitate (nume_univ, oras) values ('University of San Carlos', 'Arísvi');
insert into universitate (nume_univ, oras) values ('Governors State University', 'Zlatar');
insert into universitate (nume_univ, oras) values ('Yangzhou University', 'Voronkov');
insert into universitate (nume_univ, oras) values ('Baika Women''s College', 'Guarenas');
insert into universitate (nume_univ, oras) values ('Richard Stockton College of New Jersey', 'Ōzu');
insert into universitate (nume_univ, oras) values ('Universidad de San Buenaventura Medellin', 'Gaptsakh');
insert into universitate (nume_univ, oras) values ('University of Reading', 'Bajiazi');
insert into universitate (nume_univ, oras) values ('Myongji University', 'Qixia');
insert into universitate (nume_univ, oras) values ('Takushoku University', 'Shevchenkove');
insert into universitate (nume_univ, oras) values ('American Jewish University', 'Mirandela');
insert into universitate (nume_univ, oras) values ('Wells College', 'Pskov');
insert into universitate (nume_univ, oras) values ('Nakamura Gakuen University', 'Doksy');
insert into universitate (nume_univ, oras) values ('Cape Coast Polytechnic ', 'Vol’nyy Aul');
insert into universitate (nume_univ, oras) values ('Chicago State University', 'Ciervo Petiso');
insert into universitate (nume_univ, oras) values ('Universitas Muria Kudus', 'Patpata Segundo');
insert into universitate (nume_univ, oras) values ('Kumamoto Institute of Technology', 'Smolec');
insert into universitate (nume_univ, oras) values ('Liszt Ferenc Academy of Music Budapest', 'Kokar');
insert into universitate (nume_univ, oras) values ('Universidad de Alicante', 'Belyye Berega');
insert into universitate (nume_univ, oras) values ('Federal University of Petroleum Resources', 'Nizhnyaya Tura');
insert into universitate (nume_univ, oras) values ('Universitas 17 Agustus 1945 Jakarta', 'Baojia');
insert into universitate (nume_univ, oras) values ('Universidad Monteávila', 'Nanhuang');
insert into universitate (nume_univ, oras) values ('Ecole Nationale du Génie de l''Eau et de l''Environnement de Strasbourg', 'Zolochiv');
insert into universitate (nume_univ, oras) values ('Newschool of Architecture and Design', 'Anahawan');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Tafresh', 'Üydzen');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de la Patagonia Austral', 'Zhongguan');
insert into universitate (nume_univ, oras) values ('Universidad San Francisco Xavier', 'Pruszków');
insert into universitate (nume_univ, oras) values ('Instituto Superior de Tecnologias Avançadas - ISTEC', 'Brzeszcze');
insert into universitate (nume_univ, oras) values ('University College of Trollhättan/Uddevalla', 'Talondang');
insert into universitate (nume_univ, oras) values ('Meijo University', 'Zhouwang');
insert into universitate (nume_univ, oras) values ('Bahria University', 'Gilowice');
insert into universitate (nume_univ, oras) values ('Universidad CAECE, Buenos Aires', 'Makin Village');
insert into universitate (nume_univ, oras) values ('University of Banja Luka', 'Aqtoghay');
insert into universitate (nume_univ, oras) values ('Universiti Tun Abdul Razak', 'Sumberejo');
insert into universitate (nume_univ, oras) values ('Vitebsk State Academy of Veterinary Medicine', 'Peace River');
insert into universitate (nume_univ, oras) values ('Heartland Baptist Bible College', 'Obernai');
insert into universitate (nume_univ, oras) values ('California College San Diego', 'Basen');
insert into universitate (nume_univ, oras) values ('Dickinson State University', 'Huagu');
insert into universitate (nume_univ, oras) values ('Universidad Católica Boliviana, La Paz', 'Nanyuki');
insert into universitate (nume_univ, oras) values ('Johnson & Wales University', 'Boncong');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de San Agustin', 'Tinta');
insert into universitate (nume_univ, oras) values ('University of Macau', 'Tōbetsu');
insert into universitate (nume_univ, oras) values ('Charles R. Drew University of Medicine and Science', 'Arosbaya');
insert into universitate (nume_univ, oras) values ('Majan University College', 'Stryków');
insert into universitate (nume_univ, oras) values ('Universidad Privada San Juan Bautista', 'Kalibuntu');
insert into universitate (nume_univ, oras) values ('Egerton University', 'Czyżowice');
insert into universitate (nume_univ, oras) values ('Yerevan State Medical University', 'Muḩradah');
insert into universitate (nume_univ, oras) values ('Tamkang University', 'Progreso');
insert into universitate (nume_univ, oras) values ('Universidad Ricardo Palma', 'Roskoshnyy');
insert into universitate (nume_univ, oras) values ('Clark Atlanta University', 'Vir');
insert into universitate (nume_univ, oras) values ('University of Edinburgh', 'Mangusu');
insert into universitate (nume_univ, oras) values ('Arthur D. Little Management Education Institute', 'Jeruk');
insert into universitate (nume_univ, oras) values ('Ecole Nationale Supérieure d''Electronique et de Radioelectricite de Bordeaux', 'København');
insert into universitate (nume_univ, oras) values ('University of Tripoli', 'Níkaia');
insert into universitate (nume_univ, oras) values ('Universidade Federal do Espírito Santo', 'Budapest');
insert into universitate (nume_univ, oras) values ('University of World Economy and Diplomacy', 'Xingzi');
insert into universitate (nume_univ, oras) values ('Stockholm School of Economics in Riga', 'Changqing');
insert into universitate (nume_univ, oras) values ('Suleyman Demirel University', 'Miyazu');
insert into universitate (nume_univ, oras) values ('Universidad Juárez del Estado de Durango', 'Nabunturan');
insert into universitate (nume_univ, oras) values ('Institute of Business Administration Sukkur', 'Makīnsk');
insert into universitate (nume_univ, oras) values ('Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya', 'Jieshou');
insert into universitate (nume_univ, oras) values ('University of Targu Jiu', 'Tangwei');
insert into universitate (nume_univ, oras) values ('Mar Athanasios College for Advanced Studies', 'Danyang');
insert into universitate (nume_univ, oras) values ('Wilkes University', 'Rawang');
insert into universitate (nume_univ, oras) values ('Ohio University - Eastern', 'Hörby');
insert into universitate (nume_univ, oras) values ('Jubail University College', 'Gislaved');
insert into universitate (nume_univ, oras) values ('Chungbuk National University', 'Yenakiyeve');
insert into universitate (nume_univ, oras) values ('Mokpo National University', 'Dordrecht');
insert into universitate (nume_univ, oras) values ('Etisalat University College', 'Rano');
insert into universitate (nume_univ, oras) values ('St. Ambrose University', 'Paris 11');
insert into universitate (nume_univ, oras) values ('National College of Arts', 'Zafar');
insert into universitate (nume_univ, oras) values ('California Western School of Law', 'Kudirkos Naumiestis');
insert into universitate (nume_univ, oras) values ('Tianjin University of Commerce', 'Gayabaru');
insert into universitate (nume_univ, oras) values ('Islamic University in Uganda', 'Pigí');
insert into universitate (nume_univ, oras) values ('Manipal University', 'Podgórzyn');
insert into universitate (nume_univ, oras) values ('Bayerische Julius-Maximilians-Universität Würzburg', 'San Jerónimo');
insert into universitate (nume_univ, oras) values ('Universidad Internacional Menéndez Pelayo', 'Kyela');
insert into universitate (nume_univ, oras) values ('Manhattanville College', 'Zhaoqing');
insert into universitate (nume_univ, oras) values ('University of Alexandra Dubček in Trenčín', 'Beauvais');
insert into universitate (nume_univ, oras) values ('Sagami Women''s University', 'Svetlyy');
insert into universitate (nume_univ, oras) values ('Central Queensland University', 'Xinhui');
insert into universitate (nume_univ, oras) values ('Ummah University', 'Sigaozhuang');
insert into universitate (nume_univ, oras) values ('Kobe City University of ForeignStudies', 'Cape Town');
insert into universitate (nume_univ, oras) values ('Dordt College', 'Mancilang');
insert into universitate (nume_univ, oras) values ('Tula State University', 'Pamoyanan');
insert into universitate (nume_univ, oras) values ('King Abdullah University of Science and Technology ', 'Paarl');
insert into universitate (nume_univ, oras) values ('Carleton University', 'Gamut');
insert into universitate (nume_univ, oras) values ('Tokyo Institute of Technology', 'Rayevskiy');
insert into universitate (nume_univ, oras) values ('St. Joseph''s College of Maine', 'Miguel Hidalgo');
insert into universitate (nume_univ, oras) values ('Aleksander Gieysztor School of Humanities in Pultusk', 'Yajin');
insert into universitate (nume_univ, oras) values ('Universidad Pablo de Olavide', 'Abaetetuba');
insert into universitate (nume_univ, oras) values ('Wayland Baptist University', 'Shar’ya');
insert into universitate (nume_univ, oras) values ('Universidad de la Empresa (UDE)', 'Mostovskoy');
insert into universitate (nume_univ, oras) values ('Adygeja State University', 'Hongqi');
insert into universitate (nume_univ, oras) values ('The American University in London', 'Gostivar');
insert into universitate (nume_univ, oras) values ('Universidad Nacional Pedro Henríquez Ureña', 'Tabatinga');
insert into universitate (nume_univ, oras) values ('Faculdade Jaguariúna', 'Bryan');
insert into universitate (nume_univ, oras) values ('Universiti Malaysia Sabah', 'Popovo');
insert into universitate (nume_univ, oras) values ('Sanford-Brown Institute', 'Rio Verde de Mato Grosso');
insert into universitate (nume_univ, oras) values ('Central Academy of  Fine Art', 'Palekastro');
insert into universitate (nume_univ, oras) values ('Baghdad College of Pharmacy', 'Hrtkovci');
insert into universitate (nume_univ, oras) values ('Universidad de Antioquia', 'Baratleke');
insert into universitate (nume_univ, oras) values ('Northland College', 'Xaysetha');
insert into universitate (nume_univ, oras) values ('Imperial College London', 'Jimaguayú');
insert into universitate (nume_univ, oras) values ('Open University of the Netherlands', 'Sabi');
insert into universitate (nume_univ, oras) values ('Siebold University of Nagasaki', 'Ndofane');
insert into universitate (nume_univ, oras) values ('Yamanashi Medical University', 'Stockholm');
insert into universitate (nume_univ, oras) values ('Hanoi University of Science & Technology', 'Bafang');
insert into universitate (nume_univ, oras) values ('Shanghai Normal University', 'Sihai');
insert into universitate (nume_univ, oras) values ('Universitas Krisnadwipayana', 'Peteranec');
insert into universitate (nume_univ, oras) values ('Shanxi University', 'Fenoarivo Be');
insert into universitate (nume_univ, oras) values ('Antioch University Los Angeles', 'Piškorevci');
insert into universitate (nume_univ, oras) values ('Baker College of Flint', 'Tīkāpur');
insert into universitate (nume_univ, oras) values ('Western States Chiropractic College', 'Gaplek');
insert into universitate (nume_univ, oras) values ('Philippine Christian University', 'La Ravoire');
insert into universitate (nume_univ, oras) values ('Universidad de Castilla La Mancha', 'Santa Cruz');
insert into universitate (nume_univ, oras) values ('Weizmann Institute of Science', 'Montería');
insert into universitate (nume_univ, oras) values ('Shanghai Second Medical University', 'Sollefteå');
insert into universitate (nume_univ, oras) values ('Weizmann Institute of Science', 'Nobo');
insert into universitate (nume_univ, oras) values ('University of Maine, Orono', 'Santa Monica');
insert into universitate (nume_univ, oras) values ('Technological University (Mandalay)', 'Gujiadian');
insert into universitate (nume_univ, oras) values ('Universidad de La Salle', 'Coelho Neto');
insert into universitate (nume_univ, oras) values ('Science University of Tokyo', 'Ya‘bad');
insert into universitate (nume_univ, oras) values ('Benedictine College', 'Yoshkar-Ola');
insert into universitate (nume_univ, oras) values ('Escuela Nacional de Estudios Superiores Unidad León', 'Kawerau');
insert into universitate (nume_univ, oras) values ('European University at St.Petersburg', 'Belovo');
insert into universitate (nume_univ, oras) values ('American University Extension, Okinawa', 'Vargas');
insert into universitate (nume_univ, oras) values ('Moscow State Industrial University', 'Tuapukan');
insert into universitate (nume_univ, oras) values ('University of New York in Prague', 'Norakert');
insert into universitate (nume_univ, oras) values ('Yan Shan University', 'Muikamachi');
insert into universitate (nume_univ, oras) values ('Université Hassan Ier - Settat', 'Dallas');
insert into universitate (nume_univ, oras) values ('Kherson State University', 'Tehetu');
insert into universitate (nume_univ, oras) values ('Hehai University', 'Orlando');
insert into universitate (nume_univ, oras) values ('Chang Gung University', 'Newport');
insert into universitate (nume_univ, oras) values ('Weber State University', 'Kertasari');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Garmsar', 'Jastrzębia Góra');
insert into universitate (nume_univ, oras) values ('Université Libre de Tunis', 'Gubeikou');
insert into universitate (nume_univ, oras) values ('Warner Southern College', 'Hajnówka');
insert into universitate (nume_univ, oras) values ('Central America Health Sciences University (Belize Medical College)', 'Conde');
insert into universitate (nume_univ, oras) values ('Koforidua Polytechnic ', 'Banzhong');
insert into universitate (nume_univ, oras) values ('University of Abuja', 'San Juan de Planes');
insert into universitate (nume_univ, oras) values ('Union College Kentucky', 'Krasnystaw');
insert into universitate (nume_univ, oras) values ('Polytechnic University', 'Gyigang');
insert into universitate (nume_univ, oras) values ('Université Catholique de l'' Ouest', 'Dongjie');
insert into universitate (nume_univ, oras) values ('Universidad Isaac Newton', 'Fengzhou');
insert into universitate (nume_univ, oras) values ('God''s Bible School and College', 'Alor Star');
insert into universitate (nume_univ, oras) values ('Universitas Jayabaya', 'Sbo’o');
insert into universitate (nume_univ, oras) values ('Gulf University for Science and Technology', 'Paringin');
insert into universitate (nume_univ, oras) values ('Foshan University', 'Port Barton');
insert into universitate (nume_univ, oras) values ('United States Sports Academy', 'Corral');
insert into universitate (nume_univ, oras) values ('Universidade Católica de Angola', 'Castanheira');
insert into universitate (nume_univ, oras) values ('NAES College', 'Gaocun');
insert into universitate (nume_univ, oras) values ('Wofford College', 'Cam Ranh');
insert into universitate (nume_univ, oras) values ('Universität Paderborn', 'Graikochóri');
insert into universitate (nume_univ, oras) values ('Loughborough University', 'Sukasirna');
insert into universitate (nume_univ, oras) values ('Hogere Zeevaartschool - Maritime Academy', 'Bibai');
insert into universitate (nume_univ, oras) values ('Institut National des Sciences Appliquées de Lyon', 'Hīt');
insert into universitate (nume_univ, oras) values ('Pontifcia Universitas a S.Thomas Aquinate in Urbe', 'Hưng Nguyên');
insert into universitate (nume_univ, oras) values ('Universidad Internacional SEK, Quito', 'Kola');
insert into universitate (nume_univ, oras) values ('Shenandoah University', 'Viga');
insert into universitate (nume_univ, oras) values ('Greenheart Medical School', 'Farafangana');
insert into universitate (nume_univ, oras) values ('Technical University of Wroclaw', 'Lộc Bình');
insert into universitate (nume_univ, oras) values ('Deutsche Sporthochschule Köln', 'Jajarkrajan');
insert into universitate (nume_univ, oras) values ('Design Institute of San Diego', 'Korydallós');
insert into universitate (nume_univ, oras) values ('Seiwa College', 'Jackson');
insert into universitate (nume_univ, oras) values ('Oslo School of Architecture', 'Kayanza');
insert into universitate (nume_univ, oras) values ('Universität Ulm', 'Łaszczów');
insert into universitate (nume_univ, oras) values ('Albany College of Pharmacy', 'Pereleshino');
insert into universitate (nume_univ, oras) values ('University of Warsaw', 'Headlands');
insert into universitate (nume_univ, oras) values ('Wittenberg University', 'Kuala Lumpur');
insert into universitate (nume_univ, oras) values ('Universiti Teknologi Malaysia', 'Margamukti');
insert into universitate (nume_univ, oras) values ('Universidad Internacional del Ecuador', 'Jinquan');
insert into universitate (nume_univ, oras) values ('Universidad de La Sabana', 'Sovetakan');
insert into universitate (nume_univ, oras) values ('Fielding Institute', 'Tomar');
insert into universitate (nume_univ, oras) values ('Air Force Institute of Technology', 'Zavetnoye');
insert into universitate (nume_univ, oras) values ('French Institute of Management', 'Bordeaux');
insert into universitate (nume_univ, oras) values ('Université du Burundi', 'Ntoum');
insert into universitate (nume_univ, oras) values ('Sugiyama Jogakuen University', 'Sicheng');
insert into universitate (nume_univ, oras) values ('Edgewood College', 'Palama');
insert into universitate (nume_univ, oras) values ('Zahedan University of Medical Sciences', 'Eskilstuna');
insert into universitate (nume_univ, oras) values ('University of Guam', 'Adar');
insert into universitate (nume_univ, oras) values ('Mimasaka Women''s College', 'Non Sila');
insert into universitate (nume_univ, oras) values ('University of Belize', 'Bohdalov');
insert into universitate (nume_univ, oras) values ('University of New England', 'Lingion');
insert into universitate (nume_univ, oras) values ('Université de Picardie Jules-Verne', 'Tours');
insert into universitate (nume_univ, oras) values ('Ecole des Hautes Etudes en Gestion Informatique et Communication', 'Santa Teresita');
insert into universitate (nume_univ, oras) values ('University of Toronto, Mississauga', 'Sampir');
insert into universitate (nume_univ, oras) values ('Fachhochschule Frankfurt am Main', 'Rrapë');
insert into universitate (nume_univ, oras) values ('Universidad La Salle Cuernavaca', 'San José de Cusmapa');
insert into universitate (nume_univ, oras) values ('Zhetysu State University ', 'Fortios');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de San Agustin', 'Tullamore');
insert into universitate (nume_univ, oras) values ('Universidad Católica Argentina Santa Maria de los Buenos Aires', 'Al Jamīmah');
insert into universitate (nume_univ, oras) values ('Universität Rostock', 'Kamieniec Podolski');
insert into universitate (nume_univ, oras) values ('Fundación Universitaria de Boyacá', 'Dougou');
insert into universitate (nume_univ, oras) values ('Université d''Abobo-Adjamé', 'Sauri');
insert into universitate (nume_univ, oras) values ('Universidade de Nova Iguaçu', 'Bafoulabé');
insert into universitate (nume_univ, oras) values ('Kogakkan University', 'Boca Suno');
insert into universitate (nume_univ, oras) values ('Satakunta University Of Applied Scinces', 'Citeluk');
insert into universitate (nume_univ, oras) values ('Marist College', 'Arranhó');
insert into universitate (nume_univ, oras) values ('Soutsaka Institute of management and Technology', 'Arvidsjaur');
insert into universitate (nume_univ, oras) values ('University of Nottingham', 'Muzidian');
insert into universitate (nume_univ, oras) values ('Rajshahi University of Engineering and Technology', 'Ishinomaki');
insert into universitate (nume_univ, oras) values ('Universidad Iberoamericana', 'Besuki');
insert into universitate (nume_univ, oras) values ('Technological University (Myeik)', 'La Loma');
insert into universitate (nume_univ, oras) values ('Pjatigorsk State Linguistic University', 'Losevo');
insert into universitate (nume_univ, oras) values ('Winston-Salem State University', 'Boka');
insert into universitate (nume_univ, oras) values ('Universidad Católica de Cuyo', 'Kafr ash Shaykh');
insert into universitate (nume_univ, oras) values ('Institut National Supérieur de Formation Agro-Alimentaire', 'Dadong');
insert into universitate (nume_univ, oras) values ('Weizmann Institute of Science', 'Luba');
insert into universitate (nume_univ, oras) values ('Pädagogische Hochschule Ludwigsburg', 'Sembalunbumbung');
insert into universitate (nume_univ, oras) values ('Université Amar Telidji', 'Oslo');
insert into universitate (nume_univ, oras) values ('National American University, Colorado Springs', 'Xiaohebian');
insert into universitate (nume_univ, oras) values ('Fachhochschule Braunschweig/Wolfenbüttel', 'Hongshunli');
insert into universitate (nume_univ, oras) values ('Eugene Bible College', 'Xilong');
insert into universitate (nume_univ, oras) values ('National Chung Cheng University', 'Al Jumūm');
insert into universitate (nume_univ, oras) values ('Universidad del Bajío', 'Liuji');
insert into universitate (nume_univ, oras) values ('Dr. Hari Singh Gour University, formerly University of Sagar', 'Jacareí');
insert into universitate (nume_univ, oras) values ('Voronezh State Agricultural University', 'Los Ángeles');
insert into universitate (nume_univ, oras) values ('Politeknik Negeri Lhokseumawe', 'Březová');
insert into universitate (nume_univ, oras) values ('Universidad Autónoma de Aguascalientes', 'Villeneuve-d''Ascq');
insert into universitate (nume_univ, oras) values ('South China University', 'Santa Cecília');
insert into universitate (nume_univ, oras) values ('American University Extension, Okinawa', 'Dahua');
insert into universitate (nume_univ, oras) values ('Notre Dame University', 'Bianzhuang');
insert into universitate (nume_univ, oras) values ('Universidade de Taubaté', 'Losino-Petrovskiy');
insert into universitate (nume_univ, oras) values ('University of Twente', 'Ajuda');
insert into universitate (nume_univ, oras) values ('Pacific Union College', 'Sayama');
insert into universitate (nume_univ, oras) values ('Nakamura Gakuen University', 'Ágios Efstrátios');
insert into universitate (nume_univ, oras) values ('Institute Of Technology, Australia', 'Serrinha');
insert into universitate (nume_univ, oras) values ('Fachhochschule Westküste, Hochschule für Wirtschaft und Technik', 'Jambuwerkrajan');
insert into universitate (nume_univ, oras) values ('University Campus Suffolk', 'Cinunjang');
insert into universitate (nume_univ, oras) values ('St. Mary''s College of California', 'Biyang');
insert into universitate (nume_univ, oras) values ('Hochschule Albstadt-Sigmaringen', 'Pagatin');
insert into universitate (nume_univ, oras) values ('Vitebsk State Medical University', 'Pucara');
insert into universitate (nume_univ, oras) values ('University of Hargeisa', 'Aoqian');
insert into universitate (nume_univ, oras) values ('North Maharashtra University', 'Norfolk County');
insert into universitate (nume_univ, oras) values ('Benue State University', 'Nigríta');
insert into universitate (nume_univ, oras) values ('Universidad Técnica Particular de Loja', 'Mesyagutovo');
insert into universitate (nume_univ, oras) values ('Kamchatka State University Vitus Bering', 'Vuhlehirs’k');
insert into universitate (nume_univ, oras) values ('YPC-iTWEB College', 'Fontvieille');
insert into universitate (nume_univ, oras) values ('Siam University', 'Severoural’sk');
insert into universitate (nume_univ, oras) values ('State University of New York School of Engineering and Applied Sciences', 'Mikołów');
insert into universitate (nume_univ, oras) values ('Jamia Hamdard University', 'Lindavista');
insert into universitate (nume_univ, oras) values ('Taegu National University of Education', 'Jinhui');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de Entre Ríos', 'Fangxi');
insert into universitate (nume_univ, oras) values ('Maine Maritime Academy', 'Neebing');
insert into universitate (nume_univ, oras) values ('Ilsa Independent College', 'Korydallós');
insert into universitate (nume_univ, oras) values ('Pontificia Università Lateranense', 'Cijambe');
insert into universitate (nume_univ, oras) values ('University of Ghana', 'Świebodzice');
insert into universitate (nume_univ, oras) values ('Harbin University of Civil Engineering & Architecture', 'Impendle');
insert into universitate (nume_univ, oras) values ('St. Petersburg State University of Civil Aviation', 'Tawali');
insert into universitate (nume_univ, oras) values ('Michigan State University', 'Cete');
insert into universitate (nume_univ, oras) values ('Dar al Hekma College', 'Áno Sýros');
insert into universitate (nume_univ, oras) values ('Technical University of Liberec', 'Wakkanai');
insert into universitate (nume_univ, oras) values ('Universidad de Valladolid', 'Zeerust');
insert into universitate (nume_univ, oras) values ('Toyo Gakuen University', 'Sarband');
insert into universitate (nume_univ, oras) values ('Pontificia Università Lateranense', 'Tobatí');
insert into universitate (nume_univ, oras) values ('Global University', 'Chak Two Hundred Forty-Nine TDA');
insert into universitate (nume_univ, oras) values ('Ecole Nationale Supérieure des Industries Chimiques de Nancy', 'Mangai');
insert into universitate (nume_univ, oras) values ('Kazak National Technical University', 'El Colorado');
insert into universitate (nume_univ, oras) values ('Universidad Central del Este', 'Cibitung');
insert into universitate (nume_univ, oras) values ('Ural State Technical University', 'Chengzi');
insert into universitate (nume_univ, oras) values ('Marij State University', 'Dongfeng');
insert into universitate (nume_univ, oras) values ('New Bulgarian University', 'Shinyanga');
insert into universitate (nume_univ, oras) values ('University of Newcastle', 'Weixing');
insert into universitate (nume_univ, oras) values ('Begum Rokeya University, Rangpur', 'Bodzechów');
insert into universitate (nume_univ, oras) values ('Institute of Teachers Education, Perlis', 'Bełchatów');
insert into universitate (nume_univ, oras) values ('Lankaran State University', 'Častolovice');
insert into universitate (nume_univ, oras) values ('Pan-African University', 'Borås');
insert into universitate (nume_univ, oras) values ('Rajamangala University of Technology, Lanna Nan', 'Mineralnye Vody');
insert into universitate (nume_univ, oras) values ('Tunku Syed Sirajuddin Polytechnic', 'Bjästa');
insert into universitate (nume_univ, oras) values ('South Valley University', 'Manosque');
insert into universitate (nume_univ, oras) values ('St. Petersburg State Electrotechnical University', 'Bologoye');
insert into universitate (nume_univ, oras) values ('Kyrgyz National University', 'Larap');
insert into universitate (nume_univ, oras) values ('University of Tulsa', 'Ilongero');
insert into universitate (nume_univ, oras) values ('Helwan University', 'Lages');
insert into universitate (nume_univ, oras) values ('Universidad Autónoma de Chiapas', 'Campanário');
insert into universitate (nume_univ, oras) values ('University of California, San Diego', 'Cần Giờ');
insert into universitate (nume_univ, oras) values ('University College of Skövde', 'Dongfeng');
insert into universitate (nume_univ, oras) values ('University of Central Greece', 'Boracéia');
insert into universitate (nume_univ, oras) values ('United Business Institute', 'Bantawora');
insert into universitate (nume_univ, oras) values ('University of Wisconsin - Platteville', 'Tajumulco');
insert into universitate (nume_univ, oras) values ('Estonian University of Life Sciences', 'Sanxianling');
insert into universitate (nume_univ, oras) values ('Trinity International University', 'Severnoye');
insert into universitate (nume_univ, oras) values ('University of Nova Gorica', 'Kraljevo');
insert into universitate (nume_univ, oras) values ('Anna Maria College', 'Palamadu');
insert into universitate (nume_univ, oras) values ('Birsa Agricultural University', 'Zhuangbian');
insert into universitate (nume_univ, oras) values ('Universidad La Salle Cuernavaca', 'Luleå');
insert into universitate (nume_univ, oras) values ('Al-Birony University', 'Nong Muang');
insert into universitate (nume_univ, oras) values ('Ramkhamhaeng University', 'Palangkaraya');
insert into universitate (nume_univ, oras) values ('University of the Philippines Los Banos', 'Orkney');
insert into universitate (nume_univ, oras) values ('St. Augustine''s College North Carolina', 'Heby');
insert into universitate (nume_univ, oras) values ('Lincoln Memorial University', 'Nanterre');
insert into universitate (nume_univ, oras) values ('Universidad APEC', 'Baro Kunda');
insert into universitate (nume_univ, oras) values ('Sugiyama Jogakuen University', 'Strellc i Ulët');
insert into universitate (nume_univ, oras) values ('Iraq University College', 'Baoyang');
insert into universitate (nume_univ, oras) values ('University of the Philippines Mindanao', 'Tippi');
insert into universitate (nume_univ, oras) values ('Institut Teknologi Sepuluh Nopember', 'Skövde');
insert into universitate (nume_univ, oras) values ('Triton College', 'Kudowa-Zdrój');
insert into universitate (nume_univ, oras) values ('National Hsin-Chu Teachers College', 'Petrovo-Dal’neye');
insert into universitate (nume_univ, oras) values ('Roger Williams University', 'Ailigandí');
insert into universitate (nume_univ, oras) values ('Hiram College', 'Gedaliang');
insert into universitate (nume_univ, oras) values ('Siena Heights University', 'Koch''ang');
insert into universitate (nume_univ, oras) values ('Moscow Institute of Physics and Technology', 'Huiwan');
insert into universitate (nume_univ, oras) values ('Tzu Chi College of Medicine and Humanities', 'Quesada');
insert into universitate (nume_univ, oras) values ('Université d''Alger', 'Horton');
insert into universitate (nume_univ, oras) values ('Effat College', 'Río Colorado');
insert into universitate (nume_univ, oras) values ('Global Open University , Nagaland', 'Strassen');
insert into universitate (nume_univ, oras) values ('University of Texas at Arlington', 'Washington');
insert into universitate (nume_univ, oras) values ('Universidade Federal do ABC', 'Port Colborne');
insert into universitate (nume_univ, oras) values ('Baker College of Auburn Hills', 'Tver');
insert into universitate (nume_univ, oras) values ('Fachhochschule Bingen', 'Guhua');
insert into universitate (nume_univ, oras) values ('Fachhochschule Bonn-Rhein-Sieg', 'Ar Ru’ays');
insert into universitate (nume_univ, oras) values ('Punjab Engineering College Deemed University', 'Piñahan');
insert into universitate (nume_univ, oras) values ('Myongji University', 'Bressuire');
insert into universitate (nume_univ, oras) values ('Indira Gandhi National Open University', 'Salaza');
insert into universitate (nume_univ, oras) values ('Osaka City University', 'Markaz Bilād aţ Ţa‘ām');
insert into universitate (nume_univ, oras) values ('Roehampton University of Surrey', 'Norabats’');
insert into universitate (nume_univ, oras) values ('Universidad ICESI', 'Patabog');
insert into universitate (nume_univ, oras) values ('Royal School of Library and Information Science', 'Longquan');
insert into universitate (nume_univ, oras) values ('Beijing Union University', 'Khallat Şāliḩ');
insert into universitate (nume_univ, oras) values ('International University of Management', 'Xianhe');
insert into universitate (nume_univ, oras) values ('Universidad Empresarial', 'Mino');
insert into universitate (nume_univ, oras) values ('University of Juba', 'Ptení');
insert into universitate (nume_univ, oras) values ('Rasmussen College', 'Puning');
insert into universitate (nume_univ, oras) values ('Escuela Bancaria y Comercial', 'Nova Granada');
insert into universitate (nume_univ, oras) values ('University of Pavia', 'El Carmen');
insert into universitate (nume_univ, oras) values ('Kabardino-Balkarian State University', 'Thị Trấn Phong Thổ');
insert into universitate (nume_univ, oras) values ('Novosibirsk State University', 'Poniatowa');
insert into universitate (nume_univ, oras) values ('National University of Food Technologies', 'Nowe Grocholice');
insert into universitate (nume_univ, oras) values ('Central University of Finance and Economics', 'Bahía Honda');
insert into universitate (nume_univ, oras) values ('Université du Sud, Toulon et Var', 'Mikhaylovsk');
insert into universitate (nume_univ, oras) values ('Shanghai Sipo Polytechnic', 'Ritchie');
insert into universitate (nume_univ, oras) values ('University of Bari', 'Maodian');
insert into universitate (nume_univ, oras) values ('Academy of Fine Arts', 'Fatuhilik');
insert into universitate (nume_univ, oras) values ('Universidade Autónoma de Lisboa Luís de Camoes', 'Phù Cát');
insert into universitate (nume_univ, oras) values ('Yasuda Women''s University', 'Babahoyo');
insert into universitate (nume_univ, oras) values ('University of the Sciences in Philadelphia', 'Thị Trấn Nho Quan');
insert into universitate (nume_univ, oras) values ('Swiss Federal Institute of Technology, Zurich', 'Bratslav');
insert into universitate (nume_univ, oras) values ('University of Winnipeg', 'Cimaung Kidul');
insert into universitate (nume_univ, oras) values ('Beijing Information Science and Technology University', 'Fort Liberté');
insert into universitate (nume_univ, oras) values ('Steinbeis-Hochschule-Berlin', 'Kota Bharu');
insert into universitate (nume_univ, oras) values ('Ecole Supérieure d''Agriculture de Purpan', 'Zubrzyca Dolna');
insert into universitate (nume_univ, oras) values ('University of Nova Gorica', 'Yosowilangun');
insert into universitate (nume_univ, oras) values ('Saratov State Technical University', 'Tqibuli');
insert into universitate (nume_univ, oras) values ('Norwegian School of Management BI', 'Täby');
insert into universitate (nume_univ, oras) values ('University College of Skövde', 'Sens');
insert into universitate (nume_univ, oras) values ('Polytechnical University of Kabul', 'Tríkeri');
insert into universitate (nume_univ, oras) values ('University of Health Sciences Andhra Pradesh', 'Punkalaidun');
insert into universitate (nume_univ, oras) values ('Savannah State University', 'Aguadulce');
insert into universitate (nume_univ, oras) values ('Universidad de Puerto Rico, Cayey', 'Portelinha');
insert into universitate (nume_univ, oras) values ('Peace College', 'Huilong');
insert into universitate (nume_univ, oras) values ('Universidade Federal do Paraná', 'Magumeri');
insert into universitate (nume_univ, oras) values ('Royal College of Surgeons', 'Alvesta');
insert into universitate (nume_univ, oras) values ('Universidad Mesoamericana de San Agustín', 'Ziyuan');
insert into universitate (nume_univ, oras) values ('Princess Nora Bint Abdulrahman University', 'Tillabéri');
insert into universitate (nume_univ, oras) values ('University of Trnava', 'Seoam');
insert into universitate (nume_univ, oras) values ('Universitas Islam Sultan Agung', 'Doāba');
insert into universitate (nume_univ, oras) values ('Hochschule für Politik (HFP)', 'Olszówka');
insert into universitate (nume_univ, oras) values ('Rikkyo University (St. Paul''s University)', 'Situ');
insert into universitate (nume_univ, oras) values ('University of Sunderland', 'Tiaodeng');
insert into universitate (nume_univ, oras) values ('Mokpo National Maritime University', 'Lincoln');
insert into universitate (nume_univ, oras) values ('Hesser College', 'Miami Beach');
insert into universitate (nume_univ, oras) values ('State University of New York College at Fredonia', 'Janiuay');
insert into universitate (nume_univ, oras) values ('Noakhali University of Science and Technology', 'Kafr Kannā');
insert into universitate (nume_univ, oras) values ('Fachhochschulstudiengänge Steyr', 'Kiaranonggeng');
insert into universitate (nume_univ, oras) values ('Mississippi College', 'Madrid');
insert into universitate (nume_univ, oras) values ('Universitas Pembangunan Nasional "Veteran" East Java', 'Flushing');
insert into universitate (nume_univ, oras) values ('Rocky Mountain College of Art and Design', 'Lancaster');
insert into universitate (nume_univ, oras) values ('Colby College', 'Mentougou');
insert into universitate (nume_univ, oras) values ('Universidad Intercontinental', 'Tomepampa');
insert into universitate (nume_univ, oras) values ('Bayerische Julius-Maximilians-Universität Würzburg', 'Anaheim');
insert into universitate (nume_univ, oras) values ('Athens Laboratory of Business Administration (ALBA)', 'Baie-Comeau');
insert into universitate (nume_univ, oras) values ('Kuwait Maastricht Business School', 'La Unión');
insert into universitate (nume_univ, oras) values ('Qom University', 'Hodoš');
insert into universitate (nume_univ, oras) values ('National Technological University', 'Duofudu');
insert into universitate (nume_univ, oras) values ('Fundación Universitaria Luis Amigó', 'Qiryat Yam');
insert into universitate (nume_univ, oras) values ('University of Maryland Baltimore County', 'Qingping');
insert into universitate (nume_univ, oras) values ('Gannon University', 'Mehtar Lām');
insert into universitate (nume_univ, oras) values ('Showa Women''s University', 'Zhujiapu');
insert into universitate (nume_univ, oras) values ('Dongbei University of Finance And Economics', 'Pura');
insert into universitate (nume_univ, oras) values ('Loyola Marymount University', 'Moriki');
insert into universitate (nume_univ, oras) values ('Vologda State Pedagogical University', 'Dawangzhuang');
insert into universitate (nume_univ, oras) values ('Shanghai Television University', 'Kryvichy');
insert into universitate (nume_univ, oras) values ('Augusta State University', 'Pervomayskoye');
insert into universitate (nume_univ, oras) values ('Sathyabama University', 'Batang');
insert into universitate (nume_univ, oras) values ('Florida Community College at Jacksonville', 'Smedjebacken');
insert into universitate (nume_univ, oras) values ('Brjansk State Technical University', 'Tríkala');
insert into universitate (nume_univ, oras) values ('Universidad José Antonio Páez', 'Xinchenglu');
insert into universitate (nume_univ, oras) values ('Sunchon National University', 'Povarovo');
insert into universitate (nume_univ, oras) values ('Belarussian State Economic University', 'Fuhai');
insert into universitate (nume_univ, oras) values ('Tottori University', 'Lumbardhi');
insert into universitate (nume_univ, oras) values ('United States Naval Academy', 'Socos');
insert into universitate (nume_univ, oras) values ('Universidad de Concepción del Uruguay', 'Comallo');
insert into universitate (nume_univ, oras) values ('Universidad Cuauhtémoc', 'Postmasburg');
insert into universitate (nume_univ, oras) values ('Kharkiv State Transport Technical University', 'Beaverlodge');
insert into universitate (nume_univ, oras) values ('Universidad de Morón', 'Bamusso');
insert into universitate (nume_univ, oras) values ('Universidad Femenina del Sagrado Corazón', 'Artur Nogueira');
insert into universitate (nume_univ, oras) values ('University of the Western Cape', 'Bandung');
insert into universitate (nume_univ, oras) values ('Arab Academy for Science & Technology', 'Colombo');
insert into universitate (nume_univ, oras) values ('Augsburg College', 'San Agustin');
insert into universitate (nume_univ, oras) values ('Universidad de Magallanes', 'Kota Kinabalu');
insert into universitate (nume_univ, oras) values ('Bangladesh University', 'Toutuo');
insert into universitate (nume_univ, oras) values ('James Cook University of North Queensland', 'Vĩnh Tường');
insert into universitate (nume_univ, oras) values ('Northwood University, Texas Campus', 'Panguipulli');
insert into universitate (nume_univ, oras) values ('Cross River University of Science and Technology', 'Laoliangcang');
insert into universitate (nume_univ, oras) values ('Universitas Negeri Malang', 'Sendai-shi');
insert into universitate (nume_univ, oras) values ('Atlantic International University', 'Jezzîne');
insert into universitate (nume_univ, oras) values ('Future University', 'Fengting');
insert into universitate (nume_univ, oras) values ('Academy of Drama and Film', 'San Esteban');
insert into universitate (nume_univ, oras) values ('Hastings College', 'Peliyagoda');
insert into universitate (nume_univ, oras) values ('Magadh University', 'Nakhon Luang');
insert into universitate (nume_univ, oras) values ('Lyndon State College', 'Soutelo');
insert into universitate (nume_univ, oras) values ('Universidad Nacional del Comahue', 'Łodygowice');
insert into universitate (nume_univ, oras) values ('Universidad de Los Lagos', 'Rizal');
insert into universitate (nume_univ, oras) values ('Olivet College', 'Benito Juarez');
insert into universitate (nume_univ, oras) values ('Nanjing Medical University', 'Cherryville');
insert into universitate (nume_univ, oras) values ('University of Camerino', 'Hultsfred');
insert into universitate (nume_univ, oras) values ('Technological Education Institute of Serres', 'Lewoeleng');
insert into universitate (nume_univ, oras) values ('Universidad del Pacifico', 'Cinunjang');
insert into universitate (nume_univ, oras) values ('University Campus Suffolk', 'Maliang');
insert into universitate (nume_univ, oras) values ('Bermuda College', 'Potoci');
insert into universitate (nume_univ, oras) values ('Kurashiki University of Science and the Arts', 'Nāgarpur');
insert into universitate (nume_univ, oras) values ('American University of Paris', 'Leiden');
insert into universitate (nume_univ, oras) values ('National Law School of India University', 'Berezna');
insert into universitate (nume_univ, oras) values ('Shawnee Community College', 'Nikitinskiy');
insert into universitate (nume_univ, oras) values ('Tyumen State Agricultural Academy', 'Luna');
insert into universitate (nume_univ, oras) values ('Japan College of Social Work', 'Mākū');
insert into universitate (nume_univ, oras) values ('Catholic University of Malawi', 'Cibalung');
insert into universitate (nume_univ, oras) values ('Heartland Baptist Bible College', 'Yuanyang');
insert into universitate (nume_univ, oras) values ('Baghdad College of Economic Sciences University', 'Paris 15');
insert into universitate (nume_univ, oras) values ('Schiller International University, Heidelberg', 'Al Mughayyir');
insert into universitate (nume_univ, oras) values ('University of Wollongong - Dubai Campus', 'Luotuo');
insert into universitate (nume_univ, oras) values ('Université Mohammed V - Agdal', 'Houston');
insert into universitate (nume_univ, oras) values ('Universidad Americana', 'Chunmuying');
insert into universitate (nume_univ, oras) values ('Higher School o Business/National Louis University(WSB/NLU) in Nowy Sacz', 'Pasauran');
insert into universitate (nume_univ, oras) values ('The Emirates Academy of Hotel Managment', 'Teknāf');
insert into universitate (nume_univ, oras) values ('International Institute for Geo - Information Science and Earth Observation', 'Al Mashāf');
insert into universitate (nume_univ, oras) values ('Taj International College', 'São Miguel do Iguaçu');
insert into universitate (nume_univ, oras) values ('Western State University College of Law - Orange County', 'Kendalngupuk');
insert into universitate (nume_univ, oras) values ('ICFAI University', 'Jinluo');
insert into universitate (nume_univ, oras) values ('University of the Punjab', 'Bantu');
insert into universitate (nume_univ, oras) values ('School of Oriental and African Studies, University of London', 'Tendō');
insert into universitate (nume_univ, oras) values ('Otterbein College', 'San Isidro');
insert into universitate (nume_univ, oras) values ('Université de la Manouba', 'Norrköping');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Boukan', 'Tuochuan');
insert into universitate (nume_univ, oras) values ('University of San Agustin', 'Caoxi');
insert into universitate (nume_univ, oras) values ('Kaluga State Pedagogical University', 'Baisha');
insert into universitate (nume_univ, oras) values ('Rizal Technological University', 'Naro-Fominsk');
insert into universitate (nume_univ, oras) values ('Malayer University', 'Bourges');
insert into universitate (nume_univ, oras) values ('Suwon University', 'Perpignan');
insert into universitate (nume_univ, oras) values ('Kadir Has University', 'Sudo');
insert into universitate (nume_univ, oras) values ('Case Western Reserve University', 'Penglai');
insert into universitate (nume_univ, oras) values ('Université de Ouagadougou', 'Bom Conselho');
insert into universitate (nume_univ, oras) values ('European School of Economics', 'Bishan');
insert into universitate (nume_univ, oras) values ('Universidad Rural de Guatemala', 'Mülheim an der Ruhr');
insert into universitate (nume_univ, oras) values ('Toccoa Falls College', 'Zhongshan');
insert into universitate (nume_univ, oras) values ('United States Naval Academy', 'Nynäshamn');
insert into universitate (nume_univ, oras) values ('Kanazawa Medical University', 'Cornillon');
insert into universitate (nume_univ, oras) values ('Fachhochschule Ingolstadt', 'Ivatsevichy');
insert into universitate (nume_univ, oras) values ('University of Social Welfare and Rehabilitation Scinences', 'Baishi');
insert into universitate (nume_univ, oras) values ('Institut National des Sciences Appliquées de Toulouse', 'Sumberagung');
insert into universitate (nume_univ, oras) values ('East China Normal University', 'Shiquanhe');
insert into universitate (nume_univ, oras) values ('Akdeniz University', 'Mölndal');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de Tres de Febrero', 'Ban Takhun');
insert into universitate (nume_univ, oras) values ('Universidad Ulises Francisco Espaillat', 'Heung-hai');
insert into universitate (nume_univ, oras) values ('Kuala Lumpur Infrastructure University College', 'Laúndos');
insert into universitate (nume_univ, oras) values ('Ferris State University', 'Cilaja');
insert into universitate (nume_univ, oras) values ('Yazd Medical University', 'Méru');
insert into universitate (nume_univ, oras) values ('University of Eldoret', 'Tsagaan-Owoo');
insert into universitate (nume_univ, oras) values ('Kyushu Kyoritsu University', 'Bolszewo');
insert into universitate (nume_univ, oras) values ('American World University', 'Coroatá');
insert into universitate (nume_univ, oras) values ('School of Banking and Management in Cracow', 'Xijiang');
insert into universitate (nume_univ, oras) values ('Universidad Americana', 'Nancy');
insert into universitate (nume_univ, oras) values ('Kobe Shinwa Women''s University', 'Baijiang');
insert into universitate (nume_univ, oras) values ('University of Juba', 'Longtanping');
insert into universitate (nume_univ, oras) values ('Chubu University', 'Xinjiezi');
insert into universitate (nume_univ, oras) values ('University of Nis', 'Rio do Sul');
insert into universitate (nume_univ, oras) values ('King Fahd Security College', 'Rungis');
insert into universitate (nume_univ, oras) values ('Tabriz Islamic Art University', 'Balitai');
insert into universitate (nume_univ, oras) values ('Excelsior College', 'Truskolasy');
insert into universitate (nume_univ, oras) values ('The New School', 'Kuching');
insert into universitate (nume_univ, oras) values ('University of Tennessee - Martin', 'Ljungby');
insert into universitate (nume_univ, oras) values ('Universidad Catolica de Temuco', 'Kerkrade');
insert into universitate (nume_univ, oras) values ('University of California, Riverside', 'Baojiadian');
insert into universitate (nume_univ, oras) values ('Universitas Negeri Jakarta', 'Karamat');
insert into universitate (nume_univ, oras) values ('Emory & Henry College', 'Wetzlar');
insert into universitate (nume_univ, oras) values ('Kyushu Institute of Technology', 'Makhalino');
insert into universitate (nume_univ, oras) values ('University of Switzerland', 'Krzyżanów');
insert into universitate (nume_univ, oras) values ('Södertörn University College', 'Dýšina');
insert into universitate (nume_univ, oras) values ('Cyprus University of Technology', 'Caikouji');
insert into universitate (nume_univ, oras) values ('Hijiyama University', 'Ganshui');
insert into universitate (nume_univ, oras) values ('Osaka Gakuin University', 'Independencia');
insert into universitate (nume_univ, oras) values ('Al-Nasser University', 'Sanxi');
insert into universitate (nume_univ, oras) values ('University of Mindanao', 'Guradog');
insert into universitate (nume_univ, oras) values ('Alagappa University', 'Liaonan');
insert into universitate (nume_univ, oras) values ('Polytechnic University, Westchester Graduate Center', 'Shizi');
insert into universitate (nume_univ, oras) values ('Universidad de Colima', 'Carvalhal');
insert into universitate (nume_univ, oras) values ('Université des Sciences Sociales (Toulouse I)', 'Rivne');
insert into universitate (nume_univ, oras) values ('Arkansas State University, Newport', 'Stockholm');
insert into universitate (nume_univ, oras) values ('Universität Passau', 'Paraíba do Sul');
insert into universitate (nume_univ, oras) values ('Amman Arab University for Higher Studies', 'Shīnḏanḏ');
insert into universitate (nume_univ, oras) values ('Nanyang Technological University', 'Sammatti');
insert into universitate (nume_univ, oras) values ('Hanoi National Economics University', 'Gobernador Ingeniero Valentín Virasoro');
insert into universitate (nume_univ, oras) values ('University of Roorkee', 'Santa Cruz de Yojoa');
insert into universitate (nume_univ, oras) values ('Shenyang University', 'Lauro de Freitas');
insert into universitate (nume_univ, oras) values ('Fachhochschule Ravensburg-Weingarten', 'Point Hill');
insert into universitate (nume_univ, oras) values ('Westminster College of Salt Lake City', 'Azua');
insert into universitate (nume_univ, oras) values ('University of Groningen', 'Karpinsk');
insert into universitate (nume_univ, oras) values ('Hanover College', 'Beitou');
insert into universitate (nume_univ, oras) values ('Academy of Humanities and Economics in Lodz', 'Kentongan');
insert into universitate (nume_univ, oras) values ('Universidad de Cienfuegos', 'Niu');
insert into universitate (nume_univ, oras) values ('Holy Names College', 'Chambar');
insert into universitate (nume_univ, oras) values ('Université de Toliary', 'Jacareí');
insert into universitate (nume_univ, oras) values ('Federal Polytechnic Bauchi, Nigeria', 'Hachiōji');
insert into universitate (nume_univ, oras) values ('University of Split', 'Xanxerê');
insert into universitate (nume_univ, oras) values ('Kamakura Women''s College', 'Khon Buri');
insert into universitate (nume_univ, oras) values ('North West Frontier Province Agricultural University', 'Patrocinio');
insert into universitate (nume_univ, oras) values ('Libera Università degli Studi di Scienze Umane e Tecnologiche', 'Gelin');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Fars Science & Research Branch', 'Youzha');
insert into universitate (nume_univ, oras) values ('Emory University', 'Camalote');
insert into universitate (nume_univ, oras) values ('Abylai Khan University', 'Armopa');
insert into universitate (nume_univ, oras) values ('Okayama University of Science', 'Wenquan');
insert into universitate (nume_univ, oras) values ('Advance Tertiary College', 'Xinshancun');
insert into universitate (nume_univ, oras) values ('Kent State University - Trumbull', 'Kuala Terengganu');
insert into universitate (nume_univ, oras) values ('University of Urbino', 'Adygeysk');
insert into universitate (nume_univ, oras) values ('Franklin University', 'Aipe');
insert into universitate (nume_univ, oras) values ('Kobe Gakuin University', 'Rychwał');
insert into universitate (nume_univ, oras) values ('National Technical University (Kiev Politechnical Institute)', 'Munduk');
insert into universitate (nume_univ, oras) values ('Ecole Nationale Supérieure d''Ingénieurs en Mécanique et Energétique de Valenciennes', 'Duancun');
insert into universitate (nume_univ, oras) values ('Université de Thiès', 'Pawitan');
insert into universitate (nume_univ, oras) values ('St. Petersburg State Technological University of Plant Polymers', 'Ciputih');
insert into universitate (nume_univ, oras) values ('Universidade de Mogi das Cruzes', 'Rochester');
insert into universitate (nume_univ, oras) values ('Minneapolis College of Art and Design', 'Detchino');
insert into universitate (nume_univ, oras) values ('The College of Insurance', 'Shamkhor');
insert into universitate (nume_univ, oras) values ('Kaohsiung Medical College', 'Akita Shi');
insert into universitate (nume_univ, oras) values ('University of Burao', 'Lemery');
insert into universitate (nume_univ, oras) values ('Agriculture and Forestry University', 'San Isidro');
insert into universitate (nume_univ, oras) values ('Université Moulay Ismail Meknès', 'Koloniya Zastav’ye');
insert into universitate (nume_univ, oras) values ('Faculdade Italo Brasileira', 'Zhangcun');
insert into universitate (nume_univ, oras) values ('Universidade de Franca', 'Keluke');
insert into universitate (nume_univ, oras) values ('Sri Ramachardra Medical College and Research Institute', 'Traiguén');
insert into universitate (nume_univ, oras) values ('AGH University of Science and Technology', 'Pita Kotte');
insert into universitate (nume_univ, oras) values ('Shaqra University', 'Pavlivka');
insert into universitate (nume_univ, oras) values ('University of South Carolina - Salkehatchie', 'Gensi');
insert into universitate (nume_univ, oras) values ('Universidade Federal Rural do Semi-Árido', 'Taluksangay');
insert into universitate (nume_univ, oras) values ('Universidad Nacional Agraria de la Selva', 'Zhongshu');
insert into universitate (nume_univ, oras) values ('Anhui University of Finance and Economics', 'Louka');
insert into universitate (nume_univ, oras) values ('Technical University of Bialystok', 'Banyuurip');
insert into universitate (nume_univ, oras) values ('Universidad de Antofagasta', 'Morales');
insert into universitate (nume_univ, oras) values ('Shih Hsin University', 'Vir');
insert into universitate (nume_univ, oras) values ('Luhansk Taras Shevchenko National Pedagogical University', 'Cijangkar');
insert into universitate (nume_univ, oras) values ('Universidad Católica de Santiago del Estero', 'Épinal');
insert into universitate (nume_univ, oras) values ('Chinju National University of Education', 'Остров Пасхи');
insert into universitate (nume_univ, oras) values ('Appalachian State University', 'Youyang');
insert into universitate (nume_univ, oras) values ('Universidade Federal do Piauí', 'Catarina');
insert into universitate (nume_univ, oras) values ('University of Ontario Institute of Technology', 'Połomia');
insert into universitate (nume_univ, oras) values ('Kabul Health Sciences Institute', 'Casigua El Cubo');
insert into universitate (nume_univ, oras) values ('Gretsa Universtiy', 'Changxuanling');
insert into universitate (nume_univ, oras) values ('Escuela de Policia "General Santander"', 'Pujijie');
insert into universitate (nume_univ, oras) values ('St. Petersburg State Forest-Technical Academy', 'Berthierville');
insert into universitate (nume_univ, oras) values ('Jinnah University for Women', 'Morelos');
insert into universitate (nume_univ, oras) values ('Universitas Advent Indonesia', 'Pentecoste');
insert into universitate (nume_univ, oras) values ('Izmir Economic University', 'Kadubera');
insert into universitate (nume_univ, oras) values ('University of East Srarajevo', 'Parintins');
insert into universitate (nume_univ, oras) values ('Universidad de Los Andes', 'La Estancia');
insert into universitate (nume_univ, oras) values ('Vancouver Community College', 'Porto Martins');
insert into universitate (nume_univ, oras) values ('Regent College', 'Byumba');
insert into universitate (nume_univ, oras) values ('Latvian Academy of Arts', 'Pereira');
insert into universitate (nume_univ, oras) values ('Simmons College', 'San Julian');
insert into universitate (nume_univ, oras) values ('The University of Nottingham Ningbo China', 'Velyka Mykhaylivka');
insert into universitate (nume_univ, oras) values ('Puget Sound Christian College', 'Zhulin');
insert into universitate (nume_univ, oras) values ('Montana Tech', 'Cotabato');
insert into universitate (nume_univ, oras) values ('DeVry Institute of Technology, Irving', 'El Galpón');
insert into universitate (nume_univ, oras) values ('Al Turath University College', 'Jiaozhou');
insert into universitate (nume_univ, oras) values ('Cheljabinsk University of Agricultural Engineering', 'Buenavista');
insert into universitate (nume_univ, oras) values ('Charles R. Drew University of Medicine and Science', 'Sietesz');
insert into universitate (nume_univ, oras) values ('Barnard College - Columbia University', 'Shibetsu');
insert into universitate (nume_univ, oras) values ('Tarlac State University', 'Néa Sánta');
insert into universitate (nume_univ, oras) values ('Universidad Modular Abierta', 'Blang Dalam');
insert into universitate (nume_univ, oras) values ('Manhattanville College', 'Kore');
insert into universitate (nume_univ, oras) values ('Gujarat Ayurved University', 'Wugong');
insert into universitate (nume_univ, oras) values ('Escuela Politécnica del Ejercito', 'Yangwei');
insert into universitate (nume_univ, oras) values ('Otani University', 'Zall-Dardhë');
insert into universitate (nume_univ, oras) values ('Delaware State University', 'Aguilares');
insert into universitate (nume_univ, oras) values ('King Fahd Security College', 'Vetlanda');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Shiraz', 'Erlangkou');
insert into universitate (nume_univ, oras) values ('Université d''Antananarivo', 'Nanterre');
insert into universitate (nume_univ, oras) values ('Armstrong Atlantic State University', 'Esperanza');
insert into universitate (nume_univ, oras) values ('University of Alexandra Dubček in Trenčín', 'Smyga');
insert into universitate (nume_univ, oras) values ('Shizuoka University', 'Mobile');
insert into universitate (nume_univ, oras) values ('Kotelawala Defence University', 'Tajimi');
insert into universitate (nume_univ, oras) values ('University of Texas Health Science Center at San Antonio', 'Shigu');
insert into universitate (nume_univ, oras) values ('Libyan International Medical University (LIMU)', 'Panjakent');
insert into universitate (nume_univ, oras) values ('Universidad Pablo de Olavide', 'Birnin Kebbi');
insert into universitate (nume_univ, oras) values ('Chongju National University of Education', 'Santa Cruz');
insert into universitate (nume_univ, oras) values ('Universitas Islam Bandung', 'Bar-le-Duc');
insert into universitate (nume_univ, oras) values ('St. John Fisher College', 'Colorado Springs');
insert into universitate (nume_univ, oras) values ('Scripps College', 'Arma');
insert into universitate (nume_univ, oras) values ('Islamic Azad University, Boukan', 'Idvor');
insert into universitate (nume_univ, oras) values ('International University Institute of Luxembourg', 'Huaicheng');
insert into universitate (nume_univ, oras) values ('Moscow State Technical University of Civil Aviation', 'Bassila');
insert into universitate (nume_univ, oras) values ('Ohio Valley College', 'Racławice');
insert into universitate (nume_univ, oras) values ('Vietnam Maritime University', 'Leeuwarden');
insert into universitate (nume_univ, oras) values ('Makanlal Chutur Vedi University', 'Lũng Hồ');
insert into universitate (nume_univ, oras) values ('Kerman University of Medical Sciences', 'Banyo');
insert into universitate (nume_univ, oras) values ('CETYS Universidad', 'Welkom');
insert into universitate (nume_univ, oras) values ('Riyadh College of Dentistry and Pharmacy', 'Manogay');
insert into universitate (nume_univ, oras) values ('Universidad Autónoma de Guadalajara', 'Agbani');
insert into universitate (nume_univ, oras) values ('University College of Applied Sciences', 'Ludwin');
insert into universitate (nume_univ, oras) values ('Universidad Peruana de Ciencias Aplicadas', 'Tétouan');
insert into universitate (nume_univ, oras) values ('Escuela Colombiana de Ingeniería Julio Garavito', 'Butel');
insert into universitate (nume_univ, oras) values ('Universitas Simalungun', 'Pucara');
insert into universitate (nume_univ, oras) values ('Royal lnstitute of Technology', 'Ili');
insert into universitate (nume_univ, oras) values ('Heilongjiang August 1st Reclamation University', 'Ol’ginka');
insert into universitate (nume_univ, oras) values ('Yeditepe University', 'Sonta');
insert into universitate (nume_univ, oras) values ('University of Human Development (Kurdistan Region)', 'Yanhu');
insert into universitate (nume_univ, oras) values ('Cheju National University', 'Volot');
insert into universitate (nume_univ, oras) values ('Mahasarakham University', 'Pyu');
insert into universitate (nume_univ, oras) values ('Louisiana State University Health Sciences Center New Orleans', 'Pacajus');
insert into universitate (nume_univ, oras) values ('Universidad del Salvador', 'Bagulin');
insert into universitate (nume_univ, oras) values ('Xinjiang Agriculture University', 'Checca');
insert into universitate (nume_univ, oras) values ('State University of New York College at Geneseo', 'Chilecito');
insert into universitate (nume_univ, oras) values ('Aichi Sangyo University', 'Longchi');
insert into universitate (nume_univ, oras) values ('Universidad Nuevo Mundo', 'San Isidro');
insert into universitate (nume_univ, oras) values ('Jamia Millia Islamia University', 'Petani');
insert into universitate (nume_univ, oras) values ('Gubkin Russian State University of Oil and Gas', 'Caitang');
insert into universitate (nume_univ, oras) values ('Kasetsart University', 'Tabonok');
insert into universitate (nume_univ, oras) values ('Pace University', 'Yara');
insert into universitate (nume_univ, oras) values ('Shepherd College', 'Sanjiang');
insert into universitate (nume_univ, oras) values ('California School of Professional Psychology - Los Angels', 'Kujama');
insert into universitate (nume_univ, oras) values ('Universidad Ricardo Palma', 'Alkmaar');
insert into universitate (nume_univ, oras) values ('Kansas Wesleyan University', 'Utrecht (stad)');
insert into universitate (nume_univ, oras) values ('Technological University (Dawei)', 'Nagoselo do Douro');
insert into universitate (nume_univ, oras) values ('Nkumba University', 'Junliangcheng');
insert into universitate (nume_univ, oras) values ('Hobart and William Smith Colleges', 'Imrīsh');
insert into universitate (nume_univ, oras) values ('University of Gujrat', 'Tangwang');
insert into universitate (nume_univ, oras) values ('University of Texas at El Paso', 'San Francisco');
insert into universitate (nume_univ, oras) values ('University of Pecs', 'Omaha');
insert into universitate (nume_univ, oras) values ('Tomas Bata University in Zlin', 'Shuangxi');
insert into universitate (nume_univ, oras) values ('Columbia University', 'Culubasa');
insert into universitate (nume_univ, oras) values ('Copenhagen University', 'Independencia');
insert into universitate (nume_univ, oras) values ('Dohto University', 'Nakło nad Notecią');
insert into universitate (nume_univ, oras) values ('Ecole Superieure des Télécommunications', 'Baton Rouge');
insert into universitate (nume_univ, oras) values ('University of Marketing and Distribution Sciences', 'Matsue-shi');
insert into universitate (nume_univ, oras) values ('Fachhochschule Schwäbisch Gmünd, Hochschule für Gestaltung', 'At Tibnī');
insert into universitate (nume_univ, oras) values ('Chinese University of Hong Kong', 'Tongchuan');
insert into universitate (nume_univ, oras) values ('KDU College Sdn Bhd', 'Paris La Défense');
insert into universitate (nume_univ, oras) values ('Nilai University College', 'Buracan');
insert into universitate (nume_univ, oras) values ('Hampton University', 'Nerópolis');
insert into universitate (nume_univ, oras) values ('Georgetown University', 'Cabriz');
insert into universitate (nume_univ, oras) values ('Akdeniz University', 'Pallasovka');
insert into universitate (nume_univ, oras) values ('University of Alaska - Fairbanks', 'Gaoliang');
insert into universitate (nume_univ, oras) values ('Monmouth University', 'Alençon');
insert into universitate (nume_univ, oras) values ('Université de La Rochelle', 'Wairiang');
insert into universitate (nume_univ, oras) values ('De Montfort University Leicester', 'Banjarsari');
insert into universitate (nume_univ, oras) values ('Communication University of China', 'Kuz’minskiye Otverzhki');
insert into universitate (nume_univ, oras) values ('Lincoln University Missouri', 'Brijest');
insert into universitate (nume_univ, oras) values ('Seneca College', 'Hezhi');
insert into universitate (nume_univ, oras) values ('University of Otago', 'Sterlitamak');
insert into universitate (nume_univ, oras) values ('International University of Kagoshima', 'Cocobeach');
insert into universitate (nume_univ, oras) values ('Alabama State University', 'Longxing');
insert into universitate (nume_univ, oras) values ('Ecole Supérieure d''Ingénieurs en Génie Electrique', 'Weizhou');
insert into universitate (nume_univ, oras) values ('Universidad del País Vasco', 'Cihaurbeuti');
insert into universitate (nume_univ, oras) values ('Centre Universitaire de Technologie', 'Himaya');
insert into universitate (nume_univ, oras) values ('Principia College', 'Agpangi');
insert into universitate (nume_univ, oras) values ('Universidad de Colima', 'Alepoú');
insert into universitate (nume_univ, oras) values ('Shandong Economic University', 'Yinjiacheng');
insert into universitate (nume_univ, oras) values ('Illinois Valley Community College', 'Yumaguzino');
insert into universitate (nume_univ, oras) values ('Universidade Camilo Castelo Branco', 'Guishan');
insert into universitate (nume_univ, oras) values ('Charisma University', 'Dahua');
insert into universitate (nume_univ, oras) values ('Shaikh Zayed University', 'Hamilton');
insert into universitate (nume_univ, oras) values ('State University of West Georgia', 'La Libertad');
insert into universitate (nume_univ, oras) values ('Ivano-Frankivsk National University of Oli and Gas', 'Gotemba');
insert into universitate (nume_univ, oras) values ('Fachhochschule Burgenland', 'Kuala Lumpur');
insert into universitate (nume_univ, oras) values ('Nagoya College of Music', 'Mongaguá');
insert into universitate (nume_univ, oras) values ('University Vitez In Travnik', 'Bungkal');
insert into universitate (nume_univ, oras) values ('University of South Carolina - Salkehatchie', 'Baibu');
insert into universitate (nume_univ, oras) values ('University of NorthWest', 'Kasungu');
insert into universitate (nume_univ, oras) values ('Royal College of Surgeons', 'Tourcoing');
insert into universitate (nume_univ, oras) values ('Université Mohammed Ier', 'Xianyi');
insert into universitate (nume_univ, oras) values ('Ecole des Hautes Etudes Commerciales du Nord', 'Vazhiny');
insert into universitate (nume_univ, oras) values ('Juniata College', 'Liopétri');
insert into universitate (nume_univ, oras) values ('Zaporizhzhe National University', 'Minh Lương');
insert into universitate (nume_univ, oras) values ('Sampurnanand Sanskrit University', 'Växjö');
insert into universitate (nume_univ, oras) values ('Rocky Mountain College', 'Lamas');
insert into universitate (nume_univ, oras) values ('University of Madras', 'Futang');
insert into universitate (nume_univ, oras) values ('Omsk State Technical University', 'Liozon');
insert into universitate (nume_univ, oras) values ('Evangelische Fachhochschule Hannover', 'Echarate');
insert into universitate (nume_univ, oras) values ('South China University of Technology', 'Stockholm');
insert into universitate (nume_univ, oras) values ('Université Laval', 'Bayan');
insert into universitate (nume_univ, oras) values ('University of York', 'At Samat');
insert into universitate (nume_univ, oras) values ('Al-Ahliyya Amman University', 'Phetchaburi');
insert into universitate (nume_univ, oras) values ('Hankuk University of Foreign Studies', 'Opařany');
insert into universitate (nume_univ, oras) values ('Universidad de Ciencias y Humanidades', 'Tianxin');
insert into universitate (nume_univ, oras) values ('Babes-Bolyai University of Cluj-Napoca', 'Kępice');
insert into universitate (nume_univ, oras) values ('University Malaysia Pahang', 'Guohe');
insert into universitate (nume_univ, oras) values ('Langston University', 'Tenkodogo');
insert into universitate (nume_univ, oras) values ('Academy of Fine Arts', 'Arshaluys');
insert into universitate (nume_univ, oras) values ('University of California, Davis', 'Youlongchuan');
insert into universitate (nume_univ, oras) values ('Dr. Ram Manohar Lohia Avadh University', 'Parchowo');
insert into universitate (nume_univ, oras) values ('Chuvash State University', 'Sempu');
insert into universitate (nume_univ, oras) values ('Politeknik Negeri Jakarta', 'Latowicz');
insert into universitate (nume_univ, oras) values ('Brandenburgische Technische Universität Cottbus', 'Banjar Tegal Belodan');
insert into universitate (nume_univ, oras) values ('Université de Guelma', 'Göteborg');
insert into universitate (nume_univ, oras) values ('University of Michigan - Ann Arbor', 'Dayrūţ');
insert into universitate (nume_univ, oras) values ('University of Cagayan Valley', 'Alavieska');
insert into universitate (nume_univ, oras) values ('University of Palestine', 'Roi Et');
insert into universitate (nume_univ, oras) values ('Bridgewater State College', 'Beicheng');
insert into universitate (nume_univ, oras) values ('Bryan College', 'Iporá');
insert into universitate (nume_univ, oras) values ('Gwynedd-Mercy College', 'Baixo Guandu');
insert into universitate (nume_univ, oras) values ('Université Catholique de Lyon', 'Macarse');
insert into universitate (nume_univ, oras) values ('Universidad Cuauhtémoc', 'Curiapo');
insert into universitate (nume_univ, oras) values ('Reed College', 'Laikit, Laikit II (Dimembe)');
insert into universitate (nume_univ, oras) values ('Norwegian College of Veterinary Medicine', 'Changbao');
insert into universitate (nume_univ, oras) values ('St. Joseph''s College of Maine', 'Sóc Trăng');
insert into universitate (nume_univ, oras) values ('Universite des Sciences Islamiques de Constantine', 'Kebonsari Kidul');
insert into universitate (nume_univ, oras) values ('École Polytechnique de Montréal, Université de Montréal', 'Pato-o');
insert into universitate (nume_univ, oras) values ('Catholic University in Ružomberok', 'Voznesenskoye');
insert into universitate (nume_univ, oras) values ('Qauid-e-Awam University of Engineering Sciences & Technology', 'Mirzāpur');
insert into universitate (nume_univ, oras) values ('Wilmington College', 'Melenki');
insert into universitate (nume_univ, oras) values ('Prague International University', 'Geidam');
insert into universitate (nume_univ, oras) values ('Sanno University', 'Göteborg');
insert into universitate (nume_univ, oras) values ('Kebbi State University of Science and Technology', 'Dubovka');
insert into universitate (nume_univ, oras) values ('Université de Guelma', 'Yaroslavskaya');
insert into universitate (nume_univ, oras) values ('Universiti Teknologi Malaysia', 'Donji Dobrić');
insert into universitate (nume_univ, oras) values ('Hankyong National University', 'Ebaye');
insert into universitate (nume_univ, oras) values ('Belarussian State Economic University', 'Balīlā');
insert into universitate (nume_univ, oras) values ('Institute of Paper Science and Technology', 'Svilengrad');
insert into universitate (nume_univ, oras) values ('Norwegian University of Science and Technology', 'Dongdajie');
insert into universitate (nume_univ, oras) values ('Tiffin University', 'Cajati');
insert into universitate (nume_univ, oras) values ('The College of Wooster', 'Pingding');
insert into universitate (nume_univ, oras) values ('California College of Arts and Crafts', 'Cotia');
insert into universitate (nume_univ, oras) values ('Rusangu University', 'Blagoevgrad');
insert into universitate (nume_univ, oras) values ('Universidade de Tocantins', 'Teófilo Otoni');
insert into universitate (nume_univ, oras) values ('Morioka College', 'Changgang');
insert into universitate (nume_univ, oras) values ('Universität Osnabrück', 'Santo Niño');
insert into universitate (nume_univ, oras) values ('University of Bergen', 'Ya‘bad');
insert into universitate (nume_univ, oras) values ('New Hampshire College', 'Wang Sam Mo');
insert into universitate (nume_univ, oras) values ('Oklahoma City University', 'Shendang');
insert into universitate (nume_univ, oras) values ('Southwest Petroleum University', 'Jukui');
insert into universitate (nume_univ, oras) values ('Saudi Electronic University', 'Katoro');
insert into universitate (nume_univ, oras) values ('California School of Professional Psychology - Berkley/Alameda', 'Karmah an Nuzul');
insert into universitate (nume_univ, oras) values ('STMIK AMIKOM Yogyakarta', 'Banyuurip');
insert into universitate (nume_univ, oras) values ('Universidad de La Frontera', 'Itacorubi');
insert into universitate (nume_univ, oras) values ('Universidad Privada del Valle', 'Tayturka');
insert into universitate (nume_univ, oras) values ('Windsor University School of Medicine', 'Pushkino');
insert into universitate (nume_univ, oras) values ('Nova Scotia Agricultural College', 'Qiucun');
insert into universitate (nume_univ, oras) values ('St. Cloud State University', 'Albuquerque');
insert into universitate (nume_univ, oras) values ('University of Aden', 'Chuarrancho');
insert into universitate (nume_univ, oras) values ('Maldives National University', 'Sehwān');
insert into universitate (nume_univ, oras) values ('University of Maine, Augusta', 'Saarbrücken');
insert into universitate (nume_univ, oras) values ('Vaasa University of Applied Sciences', 'Shixiang');
insert into universitate (nume_univ, oras) values ('Texas Southern University', 'Sukamulya');
insert into universitate (nume_univ, oras) values ('University of La Verne', 'Magsaysay');
insert into universitate (nume_univ, oras) values ('Lagos State University', 'Bagorejo');
insert into universitate (nume_univ, oras) values ('Universidad Católica de Manizales', 'Cournon-d''Auvergne');
insert into universitate (nume_univ, oras) values ('Medical Academy Karol Marcinkowski in Poznan', 'Nizhniye Vyazovyye');
insert into universitate (nume_univ, oras) values ('Yerevan State University', 'Khlong Toei');
insert into universitate (nume_univ, oras) values ('Korea National Open University', 'Aldergrove');
insert into universitate (nume_univ, oras) values ('Southern Vermont College', 'Zhanbei');
insert into universitate (nume_univ, oras) values ('Higher School of University and Advanced Studies Pisa', 'Panjakent');
insert into universitate (nume_univ, oras) values ('Gonzaga University', 'Tari');
insert into universitate (nume_univ, oras) values ('Mindanao State University - Iligan Institute of Technology', 'Hejiayan');
insert into universitate (nume_univ, oras) values ('Universidade Estadual Paulista', 'Vlissingen');
insert into universitate (nume_univ, oras) values ('Nanjing University', 'Taltal');
insert into universitate (nume_univ, oras) values ('Graceland College', 'Seversk');
insert into universitate (nume_univ, oras) values ('State University of New York at Buffalo', 'Genova');
insert into universitate (nume_univ, oras) values ('Universidad Técnica Estatal de Quevedo', 'Gornyak');
insert into universitate (nume_univ, oras) values ('Buena Vista University', 'Gardawice');
insert into universitate (nume_univ, oras) values ('Ecole Supérieure de Commerce de Nantes-Atlantique', 'Ankola');
insert into universitate (nume_univ, oras) values ('Gokhale Institute of Politics and Economics', 'Villa General Belgrano');
insert into universitate (nume_univ, oras) values ('University of Wisconsin - River Falls', 'Klenica');
insert into universitate (nume_univ, oras) values ('Caldwell College', 'Zasip');
insert into universitate (nume_univ, oras) values ('Concordia College, Selma', 'Outing');
insert into universitate (nume_univ, oras) values ('Sherman College of Straight Chiropractic', 'Miami');
insert into universitate (nume_univ, oras) values ('Khabarovsk State University of Technology', 'Santa Cruz de Yojoa');
insert into universitate (nume_univ, oras) values ('Tamil Nadu Agricultural University', 'Barra do Piraí');
insert into universitate (nume_univ, oras) values ('Albertus Magnus College', 'Неготино');
insert into universitate (nume_univ, oras) values ('University of Otago', 'Tišina');
insert into universitate (nume_univ, oras) values ('Ohio University - Chillicothe', 'Jinsha');
insert into universitate (nume_univ, oras) values ('Laurentian University of Sudbury', '‘Ābūd');
insert into universitate (nume_univ, oras) values ('St. Augustine International University', 'Jomsom');
insert into universitate (nume_univ, oras) values ('Université de Mons-Hainaut', 'Tsumeb');
insert into universitate (nume_univ, oras) values ('Ashiya University', 'Otlja');
insert into universitate (nume_univ, oras) values ('Belmont University', 'København');
insert into universitate (nume_univ, oras) values ('University of Iceland', 'Żabia Wola');
insert into universitate (nume_univ, oras) values ('Wudanshan Taoist College ', 'Xunjian');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de San Luis', 'Sélestat');
insert into universitate (nume_univ, oras) values ('Pennsylvania State University - Berks-Lehigh Valley College', 'Stará Ves nad Ondřejnicí');
insert into universitate (nume_univ, oras) values ('Universidade do Estado do Rio Grande do Norte', 'Dukuh Kaler');
insert into universitate (nume_univ, oras) values ('Universidad de Almería', 'Rouen');
insert into universitate (nume_univ, oras) values ('Music Academy in Cracow', 'Klimavichy');
insert into universitate (nume_univ, oras) values ('Khana-e-Noor Institute of Higher Education', 'Ubaitaba');
insert into universitate (nume_univ, oras) values ('Virginia Polytechnic Institute and State University (Virginia Tech)', 'Diveyevo');
insert into universitate (nume_univ, oras) values ('University of Louisiana at Lafayette', 'Huaquirca');
insert into universitate (nume_univ, oras) values ('Pädagogische Hochschule Ludwigsburg', 'Bar-le-Duc');
insert into universitate (nume_univ, oras) values ('Polytechnic Institute of Turin', 'Saratak');
insert into universitate (nume_univ, oras) values ('Instituto Tecnológico de Aguascalientes', 'Kisii');
insert into universitate (nume_univ, oras) values ('University of Miskolc', 'Valdivia');
insert into universitate (nume_univ, oras) values ('University of York', 'Bánica');
insert into universitate (nume_univ, oras) values ('Belarusian-Russian University', 'Szczytno');
insert into universitate (nume_univ, oras) values ('Ballsbridge University ', 'Zielona Góra');
insert into universitate (nume_univ, oras) values ('Universidad Ulises Francisco Espaillat', 'Liren');
insert into universitate (nume_univ, oras) values ('Universidad Fray Luca Paccioli', 'Dengjia');
insert into universitate (nume_univ, oras) values ('Zagazig University', 'Zhize');
insert into universitate (nume_univ, oras) values ('Universidade Lusófona de Humanidades e Technologias', 'Meijiahe');
insert into universitate (nume_univ, oras) values ('York College Nebraska', 'Huaizhong');
insert into universitate (nume_univ, oras) values ('Fukuoka University', 'Orsk');
insert into universitate (nume_univ, oras) values ('Mount Kenya University', 'Logroño');
insert into universitate (nume_univ, oras) values ('Yamanashi Gakuin University', 'Jacinto Arauz');
insert into universitate (nume_univ, oras) values ('Riphah International Univeristy', 'Xiacang');
insert into universitate (nume_univ, oras) values ('Thomas A. Edison State College', 'Baguio');
insert into universitate (nume_univ, oras) values ('Tohwa University', 'Nanxinxiang');
insert into universitate (nume_univ, oras) values ('Universidad Nacional Pedro Henríquez Ureña', 'Akhfennir');
insert into universitate (nume_univ, oras) values ('Reitaku University', 'Paraparaumu');
insert into universitate (nume_univ, oras) values ('Western Bible College', 'Kuala Lumpur');
insert into universitate (nume_univ, oras) values ('Zetech College', 'Dongting');
insert into universitate (nume_univ, oras) values ('Instituto Superior D. Afonso III - INUAF', 'Kidričevo');
insert into universitate (nume_univ, oras) values ('Chukyo Women''s University', 'Santa Cruz La Laguna');
insert into universitate (nume_univ, oras) values ('Federal University of Technology, Akure', 'Babakantugu');
insert into universitate (nume_univ, oras) values ('Naruto University of Education', 'Shuikou');
insert into universitate (nume_univ, oras) values ('Agricultural-Technical Academy in Olsztyn', 'Santa Lucia');
insert into universitate (nume_univ, oras) values ('Ecole Nationale Supérieure Electricité et Mécanique', 'Gunungkendeng');
insert into universitate (nume_univ, oras) values ('University of Technology Jamaica', 'Lowayu');
insert into universitate (nume_univ, oras) values ('Universität Mozarteum Salzburg', 'Gushikawa');
insert into universitate (nume_univ, oras) values ('Yuan Ze University', 'Yayao');
insert into universitate (nume_univ, oras) values ('Trinity College Connecticut', 'Shanjiang');
insert into universitate (nume_univ, oras) values ('Dubai Medical College for Girls', 'Enschede');
insert into universitate (nume_univ, oras) values ('American University College of Technology', 'Novotitarovskaya');
insert into universitate (nume_univ, oras) values ('University of Montana', 'Dangchang Chengguanzhen');
insert into universitate (nume_univ, oras) values ('Sher-E-Kashmir University of Agricultural Sciences and Technology', 'Baleal');
insert into universitate (nume_univ, oras) values ('Technical University of Lodz', 'Sangkalputung');
insert into universitate (nume_univ, oras) values ('Universitas Jambi', 'Ozorków');
insert into universitate (nume_univ, oras) values ('Long Island University', 'Syanno');
insert into universitate (nume_univ, oras) values ('College of Mount St. Joseph', 'Karobokan');
insert into universitate (nume_univ, oras) values ('Silla University', 'Sadahayu');
insert into universitate (nume_univ, oras) values ('Fachhochschule Aschaffenburg', 'Jiangwan');
insert into universitate (nume_univ, oras) values ('Western Delta University', 'Las Yaras');
insert into universitate (nume_univ, oras) values ('Augustana College', 'Castelnaudary');
insert into universitate (nume_univ, oras) values ('Universidad Nacional de Santiago del Estero', 'Toki');
