-- Generated by Oracle SQL Developer Data Modeler 18.3.0.268.1156
--   at:        2018-11-30 13:58:43 EET
--   site:      Oracle Database 12cR2
--   type:      Oracle Database 12cR2



CREATE TABLE card (
    numar_card       NUMBER(16) NOT NULL,
    suma             NUMBER(10) NOT NULL,
    tip_card         VARCHAR2(10) NOT NULL,
    data_expirarii   DATE NOT NULL,
    cvv              NUMBER(3) NOT NULL,
    id_student       NUMBER(5) NOT NULL
);

ALTER TABLE card ADD CONSTRAINT card_suma_ck CHECK ( suma > 0 );

ALTER TABLE card
    ADD CONSTRAINT card_tip_card_ck CHECK ( tip_card IN (
        'GENERIC',
        'MAESTRO',
        'MASTERCARD',
        'VISA'
    ) );

CREATE UNIQUE INDEX card__idx ON
    card (
        id_student
    ASC );

ALTER TABLE card ADD CONSTRAINT card_numar_card_pk PRIMARY KEY ( numar_card );

CREATE TABLE facultate (
    id_facultate      NUMBER(2) NOT NULL,
    nume_facultate    VARCHAR2(50) NOT NULL,
    id_universitate   NUMBER(2) NOT NULL
);

ALTER TABLE facultate ADD CONSTRAINT facultate_id_facultate_pk PRIMARY KEY ( id_facultate );

CREATE TABLE locatie (
    id_locatie         NUMBER(3) NOT NULL,
    denumire_locatie   VARCHAR2(50) NOT NULL,
    adresa             VARCHAR2(150),
    telefon            VARCHAR2(10),
    comision           NUMBER(3)
);

ALTER TABLE locatie ADD CONSTRAINT locatie_comision_ck CHECK ( comision >= 0 );

ALTER TABLE locatie ADD CONSTRAINT unitate_id_unitate_pk PRIMARY KEY ( id_locatie );

CREATE TABLE student (
    id_student     NUMBER(5) NOT NULL,
    nume_stud      VARCHAR2(50) NOT NULL,
    telefon        VARCHAR2(10),
    email          VARCHAR2(50),
    id_facultate   NUMBER(2) NOT NULL,
    parola         VARCHAR2(20) NOT NULL
);

ALTER TABLE student
    ADD CONSTRAINT student_email_ck CHECK ( REGEXP_LIKE ( email,
                                                          '^\w+(\.\w+)*+@\w+(\.\w+)+$' ) );

ALTER TABLE student
    ADD CHECK ( datalength(parola) >= 4 );

ALTER TABLE student ADD CONSTRAINT student_id_student_pk PRIMARY KEY ( id_student );

ALTER TABLE student ADD CONSTRAINT student_telefon_uk UNIQUE ( telefon );

ALTER TABLE student ADD CONSTRAINT student_email_uk UNIQUE ( email );

CREATE TABLE tranzactie (
    numar_tranzactie   NUMBER(10) NOT NULL,
    tip_tranzactie     CHAR(1) NOT NULL,
    data               DATE NOT NULL,
    valoare            NUMBER(10) NOT NULL,
    id_student         NUMBER(5) NOT NULL,
    id_locatie         NUMBER(5) NOT NULL
);

ALTER TABLE tranzactie
    ADD CONSTRAINT tranzactie_tip_tranzactie_ck CHECK ( tip_tranzactie IN (
        'A',
        'C',
        'V'
    ) );

ALTER TABLE tranzactie ADD CONSTRAINT tranzactie_valoare_ck CHECK ( valoare > 0 );

ALTER TABLE tranzactie ADD CONSTRAINT tranzactie_numar_tranzactie_uk PRIMARY KEY ( numar_tranzactie );

CREATE TABLE universitate (
    id_universitate   NUMBER(2) NOT NULL,
    nume_univ         VARCHAR2(50) NOT NULL,
    oras              VARCHAR2(30) NOT NULL
);

ALTER TABLE universitate ADD CONSTRAINT universitate_id_univ_pk PRIMARY KEY ( id_universitate );

ALTER TABLE universitate ADD CONSTRAINT universitate_nume_univ_uk UNIQUE ( nume_univ );

ALTER TABLE student
    ADD CONSTRAINT facultate_student_fk FOREIGN KEY ( id_facultate )
        REFERENCES facultate ( id_facultate );

ALTER TABLE tranzactie
    ADD CONSTRAINT locatie_tranzactie_fk FOREIGN KEY ( id_locatie )
        REFERENCES locatie ( id_locatie );

ALTER TABLE card
    ADD CONSTRAINT student_card_fk FOREIGN KEY ( id_student )
        REFERENCES student ( id_student );

ALTER TABLE tranzactie
    ADD CONSTRAINT student_tranzactie_fk FOREIGN KEY ( id_student )
        REFERENCES student ( id_student );

ALTER TABLE facultate
    ADD CONSTRAINT universitate_facultate_fk FOREIGN KEY ( id_universitate )
        REFERENCES universitate ( id_universitate );

CREATE SEQUENCE facultate_id_facultate_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER facultate_id_facultate_trg BEFORE
    INSERT ON facultate
    FOR EACH ROW
    WHEN ( new.id_facultate IS NULL )
BEGIN
    :new.id_facultate := facultate_id_facultate_seq.nextval;
END;
/

CREATE SEQUENCE locatie_id_locatie_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER locatie_id_locatie_trg BEFORE
    INSERT ON locatie
    FOR EACH ROW
    WHEN ( new.id_locatie IS NULL )
BEGIN
    :new.id_locatie := locatie_id_locatie_seq.nextval;
END;
/

CREATE SEQUENCE student_id_student_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER student_id_student_trg BEFORE
    INSERT ON student
    FOR EACH ROW
    WHEN ( new.id_student IS NULL )
BEGIN
    :new.id_student := student_id_student_seq.nextval;
END;
/

CREATE SEQUENCE tranzactie_numar_tranzactie START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER tranzactie_numar_tranzactie BEFORE
    INSERT ON tranzactie
    FOR EACH ROW
    WHEN ( new.numar_tranzactie IS NULL )
BEGIN
    :new.numar_tranzactie := tranzactie_numar_tranzactie.nextval;
END;
/

CREATE SEQUENCE universitate_id_universitate START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER universitate_id_universitate BEFORE
    INSERT ON universitate
    FOR EACH ROW
    WHEN ( new.id_universitate IS NULL )
BEGIN
    :new.id_universitate := universitate_id_universitate.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           5
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
