
-- Generated by ORDS REST Data Services 18.1.1.95.1251
-- Schema: PSBDAC4  Date: Fri Jan 04 08:32:02 2019 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'PSBDAC4',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'psbd_ac4',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_base_path      => '/psbd/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'card/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'card/',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    v_id_student student.id_student%TYPE;
BEGIN
    SELECT id_student
        INTO v_id_student
        FROM student
        WHERE nume_student = :nume;
    DELETE FROM card
        WHERE id_stud = v_id_stud:
EXCEPTION
    WHEN NO_DATA_FOUNT THEN
        :status = 500;
    WHEN others THEN
        :status = 400;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'DELETE',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'DELETE',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'card/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM card');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'card/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_card EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM student
        WHERE id_student = :id_student;
    IF any_rows_found = 1 then
        RAISE e_card;
    ELSE
        INSERT INTO card(numar_card, suma, tip_card, data_expirarii, cvv, id_student)
	        VALUES(:numar_card, :suma, :tip_card, to_date(:data_expirarii, ''DD.MON.YYYY''), :cvv, :id_student);
        :status := 200;
    END IF;
EXCEPTION
    WHEN e_card THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'cvv',
      p_bind_variable_name => 'cvv',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'data_expirarii',
      p_bind_variable_name => 'data_expirarii',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'id_student',
      p_bind_variable_name => 'id_student',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'numar_card',
      p_bind_variable_name => 'numar_card',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'suma',
      p_bind_variable_name => 'suma',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/',
      p_method             => 'POST',
      p_name               => 'tip_card',
      p_bind_variable_name => 'tip_card',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'card/{nume}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'card/{nume}',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM card
WHERE id_student = (
    SELECT id_student 
    FROM student
    WHERE nume_student = :nume)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'card/{nume}',
      p_method             => 'GET',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'facultate/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'facultate/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM facultate');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'facultate/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_facult EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM facultate
        WHERE nume_facultate = :nume;
    IF any_rows_found = 1 then
        RAISE e_facult;
    ELSE
        INSERT INTO facultate(nume_facultate, id_universitate)
	        VALUES(:nume, :univ);
        :status := 200;
    END IF;
EXCEPTION
    WHEN e_facult THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
END;

');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'facultate/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'facultate/',
      p_method             => 'POST',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'facultate/',
      p_method             => 'POST',
      p_name               => 'univ',
      p_bind_variable_name => 'univ',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'facultate/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_facult EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM facultate
        WHERE nume_facultate = :nume;
    IF any_rows_found = 1 then
        UPDATE facultate
	        SET nume_facultate = :nume, id_universitate = :univ
            WHERE nume_facultate = :nume; 
        :status := 200;
    ELSE        
        RAISE e_facult;
    END IF;
EXCEPTION
    WHEN e_facult THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
END;

');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'facultate/',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'facultate/',
      p_method             => 'PUT',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'facultate/',
      p_method             => 'PUT',
      p_name               => 'univ',
      p_bind_variable_name => 'univ',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'locatie/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'locatie/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * 
FROM locatie');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'locatie/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_locatie EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM locatie
        WHERE denumire_locatie = :den_loc;
    IF any_rows_found = 1 then
        RAISE e_locatie;
    ELSE
        INSERT INTO locatie(DENUMIRE_LOCATIE, ADRESA, TELEFON, COMISION)
	        VALUES(:den_loc, :adr, :tel, :com);
        :status := 200;
    END IF;
EXCEPTION
    WHEN e_locatie THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'POST',
      p_name               => 'adr',
      p_bind_variable_name => 'adr',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'POST',
      p_name               => 'com',
      p_bind_variable_name => 'com',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'POST',
      p_name               => 'den_loc',
      p_bind_variable_name => 'den_loc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'POST',
      p_name               => 'tel',
      p_bind_variable_name => 'tel',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'locatie/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_locatie EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM locatie
        WHERE denumire_locatie = :den_loc;
    IF any_rows_found = 1 then
        UPDATE locatie
	        SET DENUMIRE_LOCATIE = :den_loc, ADRESA = :adr, TELEFON = :tel, COMISION = :com;
        :status := 200;
    ELSE
        RAISE e_locatie;
    END IF;
EXCEPTION
    WHEN e_locatie THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'PUT',
      p_name               => 'adr',
      p_bind_variable_name => 'adr',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'PUT',
      p_name               => 'com',
      p_bind_variable_name => 'com',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'PUT',
      p_name               => 'den_loc',
      p_bind_variable_name => 'den_loc',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'locatie/',
      p_method             => 'PUT',
      p_name               => 'tel',
      p_bind_variable_name => 'tel',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found_stud NUMBER;
    e_stud EXCEPTION;
    e_facult EXCEPTION;
    v_id_universitate universitate.id_universitate%TYPE;
    v_id_facultate facultate.id_facultate%TYPE;
BEGIN
    SELECT count(*)
        INTO any_rows_found_stud
        FROM student
        WHERE nume_stud = :nume;
    IF any_rows_found_stud = 1 then
        RAISE e_stud;
    ELSE
        SELECT id_universitate
            INTO v_id_universitate
            FROM universitate
            WHERE nume_univ = :n_universitate;
        SELECT id_facultate
            INTO v_id_facultate
            FROM facultate
            WHERE nume_facultate = :n_facultate AND id_universitate = v_id_universitate;
	    INSERT INTO student(nume_stud, telefon, email, parola, id_facultate)
	        VALUES(:nume, :telefon, :email, :parola, v_id_facultate);
        :status := 200;
    END IF;
EXCEPTION
    WHEN e_stud THEN 
        :status := 555;
    WHEN NO_DATA_FOUND THEN
        :status := 550;
    WHEN others THEN
        :status := 400;
end;

');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'n_facultate',
      p_bind_variable_name => 'n_facultate',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'n_universitate',
      p_bind_variable_name => 'n_universitate',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'parola',
      p_bind_variable_name => 'parola',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'POST',
      p_name               => 'telefon',
      p_bind_variable_name => 'telefon',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found_stud NUMBER;
    e_stud EXCEPTION;
    e_facult EXCEPTION;
    v_id_universitate universitate.id_universitate%TYPE;
    v_id_facultate facultate.id_facultate%TYPE;
BEGIN
    SELECT count(*)
        INTO any_rows_found_stud
        FROM student
        WHERE nume_stud = :nume;
    IF any_rows_found_stud = 1 then
        SELECT id_universitate
            INTO v_id_universitate
            FROM universitate
            WHERE nume_univ = :n_universitate;
        SELECT id_facultate
            INTO v_id_facultate
            FROM facultate
            WHERE nume_facultate = :n_facultate AND id_universitate = v_id_universitate;
	    UPDATE student
	        SET nume_stud = :nume, telefon = :telefon, email = :email, parola = :parola, id_facultate = v_id_facultate)
            WHERE nume_stud = :nume;
        :status := 200;
    ELSE
        RAISE e_stud;
    END IF;
EXCEPTION
    WHEN e_stud THEN 
        :status := 555;
    WHEN NO_DATA_FOUND THEN
        :status := 550;
    WHEN others THEN
        :status := 400;
end;

');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'email',
      p_bind_variable_name => 'email',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'n_facultate',
      p_bind_variable_name => 'n_facultate',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'n_universitate',
      p_bind_variable_name => 'n_universitate',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'parola',
      p_bind_variable_name => 'parola',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/',
      p_method             => 'PUT',
      p_name               => 'telefon',
      p_bind_variable_name => 'telefon',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/id/{id}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/id/{id}',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * 
FROM student
WHERE id_student = :id');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/id/{id}',
      p_method             => 'GET',
      p_name               => 'id',
      p_bind_variable_name => 'id',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/info/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/info/',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * FROM student');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/login/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/login/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE    
    any_rows_found NUMBER;
    v_parola student.parola%TYPE;
    e_stud EXCEPTION;
BEGIN 
    SELECT count(*)
        INTO any_rows_found
        FROM student
        WHERE nume_stud = :nume;
    IF any_rows_found = 1 then
        SELECT parola
            INTO v_parola
            FROM student
            WHERE nume_stud = :nume;
        IF v_parola = :parola THEN
            sys.htp.p(''{"autentificare": "corect"}'');
        ELSE 
            sys.htp.p(''{"autentificare": "fals", "motiv":"parola"}'');
        END IF;
    ELSE   
        RAISE e_stud;
    END IF;
EXCEPTION
    WHEN e_stud THEN 
        sys.htp.p(''{"autentificare": "fals", "motiv":"student"}'');
    WHEN NO_DATA_FOUND THEN
        sys.htp.p(''{"autentificare": "fals"}'');
    WHEN others THEN
        sys.htp.p(''{"autentificare": "fals", "motiv":"alta eroare"}'');
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/login/',
      p_method             => 'GET',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/login/',
      p_method             => 'GET',
      p_name               => 'parola',
      p_bind_variable_name => 'parola',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/nume/{nume}',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/nume/{nume}',
      p_method         => 'DELETE',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN
    DELETE FROM student
    WHERE nume_stud = :nume;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        :status = 550;
    WHEN OTHERS THEN
        :status = 400;
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/nume/{nume}',
      p_method             => 'DELETE',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/nume/{nume}',
      p_method             => 'DELETE',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'student/nume/{nume}',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT * 
FROM student
WHERE nume_stud = :nume');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'student/nume/{nume}',
      p_method             => 'GET',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'tranzactie/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'tranzactie/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM tranzactie');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'tranzactie/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found_stud NUMBER;
    any_rows_found_loc NUMBER;
    e_tranzactie EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found_stud
        FROM student
        WHERE id_student = :id_stud;
    SELECT count(*)
        INTO any_rows_found_loc
        FROM locatie
        WHERE id_locatie = :id_loc;
    IF any_rows_found_stud = 1 AND any_rows_found_loc = 1 THEN
        INSERT INTO tranzactie(tip_tranzactie, data, valoare, id_student, id_locatie)
                VALUES(:tip_tranz, :data_tranz, :val_tranz, :id_stud, :id_loc);
        IF tip_tranz = ''A'' OR tip_tranz = ''C'' THEN
            UPDATE card 
                SET suma = suma - val_tranz
                WHERE id_student = :id_stud;
        ELSEIF tip_tranz = ''V'' THEN
            UPDATE card 
                SET suma = suma + val_tranz
                WHERE id_student = :id_stud;
        END IF;
        :status := 200;
    ELSE
        RAISE e_tranzactie;
    END IF;
EXCEPTION
    WHEN e_tranzactie THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
end;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'tranzactie/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'tranzactie/',
      p_method             => 'POST',
      p_name               => 'data_tranz',
      p_bind_variable_name => 'data_tranz',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'tranzactie/',
      p_method             => 'POST',
      p_name               => 'id_loc',
      p_bind_variable_name => 'id_loc',
      p_source_type        => 'HEADER',
      p_param_type         => 'LONG',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'tranzactie/',
      p_method             => 'POST',
      p_name               => 'id_stud',
      p_bind_variable_name => 'id_stud',
      p_source_type        => 'HEADER',
      p_param_type         => 'LONG',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'tranzactie/',
      p_method             => 'POST',
      p_name               => 'tip_tranz',
      p_bind_variable_name => 'tip_tranz',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'tranzactie/',
      p_method             => 'POST',
      p_name               => 'val_tranz',
      p_bind_variable_name => 'val_tranz',
      p_source_type        => 'HEADER',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'universitate/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'universitate/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'SELECT *
FROM universitate');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'universitate/',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_univ EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM universitate
        WHERE nume_univ = :nume;
    IF any_rows_found = 1 then
        RAISE e_univ;
    ELSE
        INSERT INTO universitate(nume_univ, oras)
	        VALUES(:nume, :oras);
        :status := 200;
    END IF;
EXCEPTION
    WHEN e_univ THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
end;

');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'universitate/',
      p_method             => 'POST',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'universitate/',
      p_method             => 'POST',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'universitate/',
      p_method             => 'POST',
      p_name               => 'oras',
      p_bind_variable_name => 'oras',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'universitate/',
      p_method         => 'PUT',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'DECLARE
    any_rows_found NUMBER;
    e_univ EXCEPTION;
BEGIN
    SELECT count(*)
        INTO any_rows_found
        FROM universitate
        WHERE nume_univ = :nume;
    IF any_rows_found = 1 then
        UPDATE universitate
	        SET nume_univ = :nume, oras = :oras
            WHERE nume_univ = :nume;
        :status := 200;
    ELSE
        RAISE e_univ;
    END IF;
EXCEPTION
    WHEN e_univ THEN 
        :status := 555;
    WHEN others THEN
        :status := 400;
end;

');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'universitate/',
      p_method             => 'PUT',
      p_name               => 'X-APEX-STATUS-CODE',
      p_bind_variable_name => 'status',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'OUT',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'universitate/',
      p_method             => 'PUT',
      p_name               => 'nume',
      p_bind_variable_name => 'nume',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'oracle.studentcard.psbd',
      p_pattern            => 'universitate/',
      p_method             => 'PUT',
      p_name               => 'oras',
      p_bind_variable_name => 'oras',
      p_source_type        => 'HEADER',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'versiune/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'oracle.studentcard.psbd',
      p_pattern        => 'versiune/',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'BEGIN 
    sys.htp.p(''{"version": "1.2"}'');
END;');

    
    
COMMIT;

END;